import test from 'node:test';import assert from 'node:assert/strict';
import * as T from '../src/timeline.js';import * as C from '../src/creator.js';
import {sceneTrackOrder} from '../src/scene-core.js';
import {buildAutoEdit} from '../src/auto-edit.js';
import {creatorStyles,removeTrack,setAudioGain,applyTransitions,shortLeftovers,voiceGain,silenceRanges} from '../src/creator-workflow.js';
import {effectiveGain,mixedAudioClips} from '../src/audio-mix.js';
function fixture(){let p=T.emptyProject();p.media=[{id:'main',name:'Main.mp4',type:'video',duration:10},{id:'bg',name:'Street.mp4',type:'video',duration:3},{id:'music',name:'Music.wav',type:'audio',duration:4},{id:'logo',name:'Logo.png',type:'image',duration:10},{id:'voice',name:'Voice.wav',type:'audio',duration:10}];return p;}
const analysis={levels:Array.from({length:200},(_,i)=>i>=60&&i<100?-65:-25),windowSec:.05,peaks:[-.1,.1],peakStep:.005};
test('Auto Edit builds green-screen project with voice, repeating bg/music, fixed logo, styles and cut-attached sounds',()=>{
 const src=fixture(),before=structuredClone(src);const p=buildAutoEdit(src,{mainId:'main',green:true,key:'#147014',normalize:true,trim:true,backgroundId:'bg',bgmId:'music',logoId:'logo',style:'dynamic',transition:'whoosh',sound:true,duck:true},analysis);T.validate(p);assert.deepEqual(src,before);
 const main=p.clips.filter(c=>c.trackId==='V2'),voice=p.clips.filter(c=>c.trackId==='A1');assert.equal(main.length,2);assert.equal(main.length,voice.length);assert(main.every(c=>c.fx.chroma.enabled&&voice.some(a=>a.id===c.linkedId)));assert(p.tracks.find(t=>t.id==='A1').gainDb>0);assert(T.duration(p)<10);assert(p.tracks.find(t=>t.id==='V3').fixedOverlay);assert(p.clips.filter(c=>c.trackId==='V1').length>=3);assert(p.clips.filter(c=>c.trackId==='A2').length>=2);assert.equal(p.clips.filter(c=>c.fx.scene).length,2);assert.equal(C.transitionEvents(p).length,1);assert(C.transitionEvents(p)[0].sound);assert(!p.tracks.some(t=>t.id.startsWith('soundtrack')));assert(C.withTransitionAudio(p).tracks.some(t=>t.id.startsWith('soundtrack')));
});
test('regular Auto Edit can skip styles, transitions, trims, background and music',()=>{const p=buildAutoEdit(fixture(),{mainId:'main',voiceId:'voice',green:false,normalize:false,trim:false,style:'none',transition:'none'},analysis);assert.equal(p.clips.length,2);assert.equal(T.duration(p),10);assert(p.clips.every(c=>!c.linkedId));assert(!p.clips[0].fx.chroma.enabled);assert.equal(p.media.length,2);assert(!p.tracks.some(t=>t.creatorStyle));});
test('invalid/mismatched source and cleanup settings are rejected without modifying original',()=>{const src=fixture();assert.throws(()=>buildAutoEdit(src,{mainId:'logo'},analysis));assert.throws(()=>buildAutoEdit(src,{mainId:'main',voiceId:'music'},analysis),/shorter/);assert.throws(()=>buildAutoEdit(src,{mainId:'main',green:true},analysis),/sampling/);assert.throws(()=>buildAutoEdit(src,{mainId:'main',threshold:NaN},analysis),/Invalid/);assert.throws(()=>buildAutoEdit(src,{mainId:'main',normalize:true},null),/analysis/);assert.equal(src.clips.length,0);});
test('track removal keeps media and unlinks surviving counterpart; locked counterpart is protected',()=>{let p=T.addMediaClip(fixture(),'main','V1',0);const audio=p.clips.find(c=>c.trackId==='A1');const q=removeTrack(p,'V1');assert.equal(q.clips.length,1);assert.equal(q.clips[0].id,audio.id);assert.equal(q.clips[0].linkedId,null);assert.equal(q.media.length,p.media.length);assert.equal(p.clips.length,2);p={...p,tracks:p.tracks.map(t=>t.id==='A1'?{...t,locked:true}:t)};assert.throws(()=>removeTrack(p,'V1'),/Unlock/);assert.throws(()=>removeTrack(p,'A1'),/Unlock/);});
test('clip, selected and master-track gain share preview/export values without altering other clips',()=>{let p=T.addMediaClip(fixture(),'main','V1',0);p={...p,clips:p.clips.map(c=>c.trackId==='A1'?{...c,fx:{...c.fx,gainDb:0}}:c)};p=T.splitClips(p,p.clips[0].id,5);const a=p.clips.filter(c=>c.trackId==='A1');p=setAudioGain(p,{scope:'clip',clipId:a[0].id,db:3});p=setAudioGain(p,{scope:'track',trackId:'A1',db:4});assert.equal(effectiveGain(p,p.clips.find(c=>c.id===a[0].id)),7);assert.equal(effectiveGain(p,p.clips.find(c=>c.id===a[1].id)),4);assert.deepEqual(mixedAudioClips(p).map(c=>c.fx.gainDb),[7,4]);p=setAudioGain(p,{scope:'selected',ids:a.map(c=>c.linkedId),db:2});assert(mixedAudioClips(p).every(c=>c.fx.gainDb===6));assert.throws(()=>setAudioGain(p,{scope:'track',trackId:'A1',db:100}));});
test('BGM ducking uses matching preview/export intervals and follows voice mute',()=>{const p=buildAutoEdit(fixture(),{mainId:'main',bgmId:'music',bgmDb:-20,duck:true},analysis);const voice=p.clips.find(c=>c.trackId==='A1');voice.duration=2;voice.linkedId=null;p.clips.find(c=>c.trackId==='V2').linkedId=null;const bgm=p.clips.find(c=>c.trackId==='A2');assert.equal(effectiveGain(p,bgm,1),-30);assert.equal(effectiveGain(p,bgm,3),-20);const exported=mixedAudioClips(p).filter(c=>c.trackId==='A2');assert.equal(exported[0].duration,2);assert.equal(exported[0].fx.gainDb,-30);assert.equal(exported[1].fx.gainDb,-20);const muted={...p,tracks:p.tracks.map(t=>t.id==='A1'?{...t,muted:true}:t)};assert.equal(effectiveGain(muted,bgm,1),-20);});
test('short cleanup is conservative by default, aggressive explicitly includes speech, source offsets respected',()=>{const p={...T.emptyProject(),clips:[{id:'a',trackId:'A1',sourceIn:0,start:0,duration:1},{id:'b',trackId:'A1',sourceIn:1,start:1,duration:1},{id:'c',trackId:'A1',sourceIn:2,start:2,duration:3}]};const data={windowSec:.05,levels:[...Array(20).fill(-65),...Array(80).fill(-20)]};assert.deepEqual(shortLeftovers(p,'A1',()=>data).map(c=>c.id),['a']);assert.deepEqual(shortLeftovers(p,'A1',()=>data,{allShort:true,maxDuration:2}).map(c=>c.id),['a','b']);assert.deepEqual(shortLeftovers(p,'A1',()=>null),[]);});
test('both style defaults roundtrip; full-video transitions require replace consent and stay cut-attached',()=>{for(const s of creatorStyles)assert.deepEqual(C.validateStyle(JSON.parse(JSON.stringify(s))),s);let p=T.addMediaClip(fixture(),'main','V1',0);p=T.splitClips(p,p.clips[0].id,5);const preset={...C.transitionPreset('paper'),sound:false};const q=applyTransitions(p,{trackId:'V1',all:true,preset});assert.equal(q.tracks.length,p.tracks.length);assert.equal(C.transitionEvents(q).length,1);assert(!C.transitionEvents(q)[0].sound);assert.throws(()=>applyTransitions(q,{trackId:'V1',all:true,preset}),/Replace/);assert.equal(C.transitionEvents(applyTransitions(q,{trackId:'V1',all:true,preset,replace:true})).length,1);});
test('voice adjustment is peak-safe, silence detection preserves padding and never mutates analysis',()=>{assert.equal(voiceGain({levels:[-30,-29,-31],peaks:[-.9,.9]}),-.1);const before=structuredClone(analysis),rs=silenceRanges({start:5,sourceIn:0,duration:10},analysis);assert(rs[0][0]>8&&rs[0][1]<10);assert.deepEqual(analysis,before);});
test('default silence detection ignores room tone above −62 dB but user-selected thresholds still detect it',()=>{const a={levels:[...Array(20).fill(-20),...Array(20).fill(-50),...Array(20).fill(-20)],windowSec:.05};const clip={start:0,sourceIn:0,duration:3};assert.deepEqual(silenceRanges(clip,a),[]);assert(silenceRanges(clip,a,{threshold:-38}).length>0);});

test('logo stays above scene styles by default; include-logo option restores whole-scene order',()=>{
 const p=buildAutoEdit(fixture(),{mainId:'main',logoId:'logo',style:'simple'},analysis);
 assert.equal(sceneTrackOrder(p,0).at(-1).id,'V3');
 for(const c of p.clips.filter(c=>c.fx.scene))c.fx.scene.includeLogo=true;
 assert(sceneTrackOrder(p,0).at(-1).creatorStyle);
 const hidden={...p,tracks:p.tracks.map(t=>t.creatorStyle?{...t,hidden:true}:t)};
 assert.equal(sceneTrackOrder(hidden,0).at(-1).id,'V3');
});
test('Auto Edit carries manual crop and protected subject into footage and conservative styles',()=>{const crop={left:.1,right:.05,top:0,bottom:.08},subject={x:.24,y:.05,width:.48,height:.86,headroom:.05};const p=buildAutoEdit(fixture(),{mainId:'main',green:false,style:'dynamic',crop,subject},analysis);const main=p.clips.find(c=>c.trackId==='V2');assert.deepEqual(main.fx.crop,crop);assert.deepEqual(main.fx.subject,subject);const style=p.clips.find(c=>c.fx?.scene);assert(style.fx.scene.subjectSafe);assert(style.fx.scene.from.scale<=Math.floor(100/Math.max(subject.width,subject.height+subject.headroom))*1.01);});
