import React,{useState} from 'react';
import * as T from './timeline.js';
import {shortLeftovers} from './creator-workflow.js';
export default function LeftoverCleanup({project,media,trackId,commit,seek}){
 const [max,setMax]=useState(2),[threshold,setThreshold]=useState(-30),[aggressive,setAggressive]=useState(false),[review,setReview]=useState(null),[error,setError]=useState('');
 const detect=()=>{try{const clips=project.clips.filter(c=>c.trackId===trackId);if(!clips.length)throw Error('Choose a main video or voice track.');if(clips.some(c=>!media.find(m=>m.id===c.mediaId)?.levels?.length))throw Error('Wait for audio analysis on this track.');const rows=shortLeftovers(project,trackId,c=>media.find(m=>m.id===c.mediaId),{maxDuration:max,threshold,allShort:aggressive});setReview({revision:project,rows});setError('');}catch(e){setError(e.message);}};
 const remove=()=>{if(review.revision!==project){setError('Timeline changed. Scan leftovers again.');return;}if(review.rows.length&&confirm('Remove '+review.rows.length+' short pieces and ripple all tracks? Review may include speech; Undo can restore it.')){commit(p=>T.removeRanges(p,review.rows.map(x=>x.range),{ripple:true}),'Short leftovers removed');setReview(null);}};
 return <details className="leftoverCleanup"><summary>Clean short leftovers</summary><p>Scan after silence cutting. Mostly quiet clips only by default; not cough recognition.</p><label>Maximum length (s)<input aria-label="Leftover maximum duration" type="number" min=".2" max="3" step=".1" value={max} onChange={e=>{setMax(T.clamp(+e.target.value,.2,3));setReview(null);}}/></label><label>Quiet threshold (dB)<input type="number" min="-65" max="-15" value={threshold} onChange={e=>{setThreshold(T.clamp(+e.target.value,-65,-15));setReview(null);}}/></label><label><input type="checkbox" checked={aggressive} onChange={e=>{setAggressive(e.target.checked);setReview(null);}}/> Aggressive: include ALL short clips (can remove speech)</label><button onClick={detect}>Scan leftovers on this track</button>{review&&<><p>{review.rows.length} candidates</p>{review.rows.map(row=><div className="cleanupRow" key={row.id}><button onClick={()=>seek(row.range[0])}>{row.range[0].toFixed(2)}s · {(row.range[1]-row.range[0]).toFixed(2)}s</button><button onClick={()=>setReview({...review,rows:review.rows.filter(x=>x.id!==row.id)})}>Keep</button></div>)}<button disabled={!review.rows.length||review.revision!==project} onClick={remove}>Remove reviewed pieces + ripple</button></>}{error&&<p role="alert" className="exportError">{error}</p>}</details>;
}
