import test from 'node:test';import assert from 'node:assert/strict';
import * as T from '../src/timeline.js';import * as C from '../src/creator.js';import * as E from '../src/editing.js';import {motionAt} from '../src/scene-core.js';import {synthesizedSound,soundBytes} from '../src/sounds.js';
function fixture(){let p=T.emptyProject();p.media=[{id:'v',type:'video',name:'talk',duration:12},{id:'bg',type:'image',name:'bg',duration:12}];p=T.addMediaClip(p,'v','V1',0);p=T.splitClips(p,p.clips[0].id,4);const right=p.clips.find(c=>c.trackId==='V1'&&c.start===4);p=T.splitClips(p,right.id,8);p=T.addTrack(p,'video');p=T.addMediaClip(p,'bg','V2',0);return p;}
test('Style generates whole-scene adjustment segments without modifying footage or attaching transitions',()=>{const p=fixture(),q=C.applyStyle(p,'V1',C.builtInStyle,123);assert.equal(q.tracks[0].creatorStyle,true);assert.equal(T.addTrack(q,'video').tracks[0].creatorStyle,true);for(const c of p.clips)assert.deepEqual(q.clips.find(x=>x.id===c.id),c);const styles=q.clips.filter(c=>c.kind==='adjustment');assert.deepEqual(styles.map(c=>[c.start,c.duration]),[[0,4],[4,4],[8,4]]);assert.equal(C.transitionEvents(q).length,0);assert.notEqual(styles[0].name,styles[1].name);assert.notEqual(styles[1].name,styles[2].name);assert.deepEqual(C.applyStyle(p,'V1',C.builtInStyle,123).clips.filter(c=>c.kind==='adjustment').map(c=>c.fx),styles.map(c=>c.fx));});
test('regenerate respects locked Style segments and rejects locked track',()=>{let p=C.applyStyle(fixture(),'V1',C.builtInStyle,4);const c=p.clips.find(c=>c.kind==='adjustment');c.styleLocked=true;const q=C.applyStyle(p,'V1',C.builtInStyle,99);assert.deepEqual(q.clips.find(x=>x.id===c.id),c);p.tracks[0].locked=true;assert.throws(()=>C.applyStyle(p,'V1',C.builtInStyle,1),/Unlock/);});
test('Style animated framing survives trim with progress preserved',()=>{let p=C.applyStyle(fixture(),'V1',{...C.builtInStyle,shots:[C.builtInStyle.shots[2]]},1);const c=p.clips.find(c=>c.kind==='adjustment');const before=motionAt(c,2);p=T.removeRanges(p,[[0,1]]);const after=p.clips.find(c=>c.kind==='adjustment'&&c.start===0);assert.deepEqual(motionAt(after,1),before);assert(motionAt(after,2).scale>before.scale);});
test('Style JSON round trip validates bounds and isolates input',()=>{const v=C.validateStyle(JSON.parse(JSON.stringify(C.builtInStyle)));v.shots[0].from.scale=120;assert.equal(C.builtInStyle.shots[0].from.scale,100);assert.throws(()=>C.validateStyle({...v,shots:[{...v.shots[0],from:{scale:NaN,x:0,y:0}}]}),/Style scale/);});
test('manual transition and sound follow a moved cut, disappear with deletion, and do not duplicate on split',()=>{let p=fixture(),right=p.clips.find(c=>c.trackId==='V1'&&c.start===4);p=C.attachTransition(p,right.id,C.transitionPreset('paper'));const event=C.transitionEvents(p)[0];assert.equal(event.cut,4);assert.equal(C.withTransitionAudio(p).clips.filter(c=>c.id.startsWith('sound_')).length,1);const moved=E.moveGroup(p,p.clips.filter(c=>c.trackId==='V1'||c.trackId==='A1').map(c=>c.id),p.clips.find(c=>c.trackId==='V1'&&c.start===0).id,'V1',1);assert.equal(C.transitionEvents(moved)[0].cut,5);const split=T.splitClips(p,right.id,6);assert.equal(C.transitionEvents(split).length,1);const deleted=T.deleteClips(p,right.id);assert.equal(C.transitionEvents(deleted).length,0);assert.equal(C.withTransitionAudio(deleted).clips.filter(c=>c.id.startsWith('sound_')).length,0);});
test('duration changes do not stretch sound; disabling and unlinking work',()=>{let p=fixture();const right=p.clips.find(c=>c.trackId==='V1'&&c.start===4);p=C.attachTransition(p,right.id,{...C.transitionPreset(),duration:1.5});const sound=C.withTransitionAudio(p).clips.find(c=>c.id.startsWith('sound_'));assert.equal(sound.duration,.5);assert.equal(sound.start,3.75);const q=C.unlinkSound(p,right.id);assert.equal(q.clips.find(c=>c.id===right.id).transition.sound,false);assert(q.media.some(m=>m.sound));assert.equal(q.clips.filter(c=>c.name==='whoosh sound').length,1);T.validate(q);});
test('embedded sound preset round-trip is lossless and malformed WAV is rejected',()=>{const bytes=synthesizedSound('paper'),preset={...C.transitionPreset('paper'),customSound:{name:'Paper',duration:.5,data:Buffer.from(bytes).toString('base64')}};const v=C.validateTransition(JSON.parse(JSON.stringify(preset)));assert.deepEqual(soundBytes(v.customSound),bytes);assert.throws(()=>C.validateTransition({...preset,customSound:{...preset.customSound,duration:2}}),/mismatch/);assert.throws(()=>C.validateTransition({...preset,customSound:{...preset.customSound,data:'AAAA'}}),/Invalid/);});
test('no transition on first clip or gap; locked footage rejects attach',()=>{let p=fixture(),right=p.clips.find(c=>c.trackId==='V1'&&c.start===4);assert.throws(()=>C.attachTransition(p,p.clips.find(c=>c.trackId==='V1'&&c.start===0).id,C.transitionPreset()),/actual cut/);p.tracks.find(t=>t.id==='V1').locked=true;assert.throws(()=>C.attachTransition(p,right.id,C.transitionPreset()),/Unlock/);});
