import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,readFile,rm,stat} from 'node:fs/promises';import {existsSync} from 'node:fs';import os from 'node:os';import path from 'node:path';import {createServer} from 'node:http';import {createRequire} from 'node:module';import {spawnSync} from 'node:child_process';
import {outputStore} from '../src/output-store.js';import {createApi} from '../server.mjs';import {fitZoom,boxSelection} from '../src/timeline-view.js';import * as T from '../src/timeline.js';import {selectFrom,moveGroup} from '../src/editing.js';
const require=createRequire(import.meta.url),binary=process.env.RANCUT_FFMPEG||require('ffmpeg-static');
test('Fit covers 20-minute and 4-hour timelines; box-selection intersects the correct unlocked lanes',()=>{for(const duration of [1200,14400])assert(fitZoom(800,duration)*(duration+2)<=800+.001);let p=T.emptyProject();p.media=[{id:'v',type:'video',duration:10,name:'v'}];p=T.addMediaClip(p,'v','V1',0);assert.equal(boxSelection(p,{left:10,top:31,width:200,height:90},80).length,2);p.tracks[1].locked=true;assert.equal(boxSelection(p,{left:10,top:31,width:200,height:90},80).length,1);});
test('from selected clip to end selects following unlocked clips and moves linked pairs together',()=>{let p=T.emptyProject();p.media=[{id:'v',type:'video',duration:10,name:'v'}];p=T.addMediaClip(p,'v','V1',0);p=T.splitClips(p,p.clips[0].id,3);const right=p.clips.find(c=>c.trackId==='V1'&&c.start===3);p=T.splitClips(p,right.id,6);const anchor=p.clips.find(c=>c.trackId==='V1'&&c.start===3),ids=selectFrom(p,anchor.id);assert.equal(ids.length,4);const q=moveGroup(p,ids,anchor.id,'V1',5);assert.deepEqual(q.clips.filter(c=>c.trackId==='V1').map(c=>c.start),[0,5,8]);assert.equal(selectFrom(p,anchor.id,false).length,2);});
test('output folder is remembered across store instances',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'rancut-output-'));try{const cfg={defaultDirectory:path.join(root,'default'),settingsPath:path.join(root,'settings.json')},store=await outputStore(cfg);assert.equal(store.get(),cfg.defaultDirectory);await store.set(path.join(root,'chosen'));assert.equal((await outputStore(cfg)).get(),path.join(root,'chosen'));await assert.rejects(()=>store.set('relative'),/absolute/);}finally{await rm(root,{recursive:true,force:true});}});
test('raw-frame MP4 auto-saves, has upright orientation and survives app cleanup; cancel leaves no published file',{skip:!binary||!existsSync(binary)},async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'rancut-raw-')),api=await createApi({ffmpeg:binary,exportDir:path.join(root,'out'),settingsPath:path.join(root,'settings.json')}),server=createServer(api.middleware);await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}/api/`;
 const post=async(url,data,raw=false)=>{const res=await fetch(base+url,{method:'POST',headers:{'X-RanCut':'1','Content-Type':raw?'application/octet-stream':'application/json'},body:raw?data:JSON.stringify(data)});const j=await res.json();assert.equal(res.status,200,JSON.stringify(j));return j;};
 let savedPath;
 try{
 const cfg={width:64,height:64,fps:30,frames:2,frameFormat:'rgba',quality:'High',audio:[]},job=await post('export',cfg),frame=Buffer.alloc(64*64*4);for(let y=0;y<64;y++)for(let x=0;x<64;x++){const n=(y*64+x)*4;frame[n+(y<32?0:2)]=255;frame[n+3]=255;}
 await post(`export/${job.id}/frame?index=0`,frame,true);await post(`export/${job.id}/frame?index=1`,frame,true);await post(`export/${job.id}/finish`,{});let state;
 for(let i=0;i<100;i++){state=await(await fetch(base+`export/${job.id}/status`)).json();if(['complete','failed'].includes(state.state))break;await new Promise(r=>setTimeout(r,50));}
 assert.equal(state.state,'complete',state.error);savedPath=state.savedPath;assert(savedPath.startsWith(path.join(root,'out')));assert((await stat(savedPath)).size>1000);
 const decoded=spawnSync(binary,['-v','error','-i',savedPath,'-frames:v','1','-f','rawvideo','-pix_fmt','rgb24','pipe:1']);assert.equal(decoded.status,0);assert(decoded.stdout[2]>200&&decoded.stdout[0]<30,'top row should be blue after vertical flip');
 const cancelled=await post('export',cfg);await post(`export/${cancelled.id}/cancel`,{});const c=await(await fetch(base+`export/${cancelled.id}/status`)).json();assert.equal(c.state,'cancelled');assert.equal(c.savedPath,null);
 }finally{await new Promise(r=>server.close(r));await api.cleanup();if(savedPath)assert((await readFile(savedPath)).length>1000);await rm(root,{recursive:true,force:true});}
});
