import test from 'node:test';
import assert from 'node:assert/strict';
import * as T from '../src/timeline.js';
import * as E from '../src/editing.js';
import {audioFilter} from '../src/audio-filter.js';
function fixture(){let p=T.emptyProject();p.media=[{id:'v',type:'video',duration:20,name:'v'},{id:'bg',type:'image',duration:20,name:'bg'}];return T.addMediaClip(p,'v','V1',0);}
test('atomic multi-move: adjacent clips and both linked partners move once',()=>{let p=fixture();p=T.splitClips(p,p.clips[0].id,5);const q=E.moveGroup(p,p.clips.map(c=>c.id),p.clips[0].id,'V1',2);for(const c of q.clips)assert.equal(c.start,p.clips.find(x=>x.id===c.id).start+2);T.validate(q);});
test('group clamps as a unit at timeline zero and rejects collisions/locks',()=>{let p=fixture();p=T.splitClips(p,p.clips[0].id,5);const right=p.clips.find(c=>c.start===5&&c.trackId==='V1');const q=E.moveGroup(p,p.clips.map(c=>c.id),right.id,'V1',0);assert.deepEqual(q.clips.map(c=>c.start),p.clips.map(c=>c.start));assert.throws(()=>E.moveGroup(p,[right.id],right.id,'V1',4),/Overlap/);p.tracks[1].locked=true;assert.throws(()=>E.moveGroup(p,[right.id],right.id,'V1',7),/Unlock/);});
test('gap detection includes leading gap, and one gap closure keeps later gaps',()=>{let p=fixture();p=T.splitClips(p,p.clips[0].id,5);const right=p.clips.find(c=>c.start===5&&c.trackId==='V1');p=E.moveGroup(p,[right.id],right.id,'V1',7);p=E.moveGroup(p,p.clips.map(c=>c.id),p.clips[0].id,'V1',3);assert.deepEqual(E.gapsOnTrack(p,'V1'),[[0,3],[8,10]]);const q=E.scopedRemove(p,[[0,3]]);assert.deepEqual(E.gapsOnTrack(q,'V1'),[[5,7]]);const r=E.scopedRemove(p,E.gapsOnTrack(p,'V1'));assert.deepEqual(E.gapsOnTrack(r,'V1'),[]);});
test('all-unlocked crop leaves unrelated locked background unchanged',()=>{let p=fixture();p=T.addTrack(p,'video');p=T.addMediaClip(p,'bg','V2',0);p.tracks.find(t=>t.id==='V2').locked=true;const bg=p.clips.find(c=>c.trackId==='V2');const q=E.scopedRemove(p,[[0,3]]);assert.deepEqual(q.clips.find(c=>c.id===bg.id),bg);assert.equal(q.clips.find(c=>c.trackId==='V1').sourceIn,3);p.tracks.find(t=>t.id==='A1').locked=true;assert.throws(()=>E.scopedRemove(p,[[0,3]]),/Unlock/);});
test('selected crop preserves other layers and relinks selected audio',()=>{let p=fixture();p=T.addTrack(p,'video');p=T.addMediaClip(p,'bg','V2',0);const id=p.clips.find(c=>c.trackId==='V1').id;const q=E.scopedRemove(p,[[0,4]],{scope:'selected',ids:[id]});assert.equal(q.clips.find(c=>c.trackId==='V2').duration,20);assert.equal(q.clips.find(c=>c.trackId==='V1').duration,16);T.validate(q);});
test('W ripple trim stops at the selected clip end and keeps later background content',()=>{let p=T.emptyProject();p.media=[{id:'main',type:'video',name:'main',duration:15},{id:'bg',type:'image',name:'bg',duration:25}];p=T.addMediaClip(p,'main','V1',0);p=T.splitClips(p,p.clips.find(c=>c.trackId==='V1').id,5);p=T.addTrack(p,'video');p=T.addMediaClip(p,'bg','V2',0);const selected=p.clips.find(c=>c.trackId==='V1'&&c.start===5);const result=E.rippleTrimRight(p,selected.id,10,{scope:'all',ids:[selected.id]});assert.deepEqual(result.range,[10,15]);assert.equal(result.targetEnd,15);assert.equal(T.duration(result.project),20);assert.deepEqual(result.project.clips.filter(c=>c.trackId==='V1').map(c=>[c.start,c.duration]),[[0,5],[5,5]]);assert.deepEqual(result.project.clips.filter(c=>c.trackId==='V2').map(c=>[c.start,c.duration]),[[0,10],[10,10]]);T.validate(result.project);});
test('effect copy is deep, scoped, undo-safe and obeys lock',()=>{const p=fixture(),id=p.clips[0].id,fx=T.fxDefault();fx.chroma.threshold=.3;const q=E.pasteEffects(p,[id],fx,'chroma');fx.chroma.threshold=.5;assert.equal(q.clips[0].fx.chroma.threshold,.3);assert.equal(p.clips[0].fx.chroma.threshold,.14);assert.equal(q.clips[1].fx.chroma.threshold,.14);p.tracks[0].locked=true;assert.throws(()=>E.pasteEffects(p,[id],fx),/Unlock/);});
test('fade endpoints, short clips, disabled mode and export parity',()=>{const c={start:3,duration:.006,fx:{fadeMs:20}};assert.equal(E.fadeDuration(c),.003);assert.equal(E.envelope(c,3),0);assert(Math.abs(E.envelope(c,3.003)-1)<1e-8);assert.equal(E.envelope(c,3.006),0);const a={start:3,sourceIn:1,duration:.006,fadeMs:20,gainDb:0};assert.match(audioFilter(a,1,0),/afade=t=in:st=0:d=0.003,afade=t=out:st=0.003:d=0.003/);assert(!audioFilter({...a,fadeMs:0},1,0).includes('afade'));});
