import test from 'node:test';
import assert from 'node:assert/strict';
import * as T from '../src/timeline.js';
function fixture(){let p=T.emptyProject();p.media=[{id:'v',type:'video',name:'talk.mp4',duration:20},{id:'bg',type:'image',name:'bg.png',duration:20}];p=T.addMediaClip(p,'v','V1',0);return p;}
test('exclusive end: exactly one adjacent clip active at cut',()=>{let p=fixture();p=T.splitClips(p,p.clips[0].id,5);assert.equal(T.activeAt(p,5).filter(c=>c.trackId==='V1').length,1);assert.equal(T.activeAt(p,20).length,0);});
test('reject additions, moves and non-ripple extensions that overlap',()=>{let p=fixture();assert.throws(()=>T.addMediaClip(p,'v','V1',2),/Overlap/);p=T.splitClips(p,p.clips[0].id,5);const c=p.clips.find(c=>c.trackId==='V1'&&c.start===5);assert.throws(()=>T.moveClip(p,c.id,'V1',4),/Overlap/);const left=p.clips.find(c=>c.trackId==='V1'&&c.start===0);assert.throws(()=>T.resizeClip(p,left.id,'right',6,false),/Overlap/);});
test('multiple silence cuts compact video and linked audio identically',()=>{const p=fixture();const q=T.removeRanges(p,[[2,3],[5,7]],{ripple:true});for(const t of ['V1','A1'])assert.deepEqual(q.clips.filter(c=>c.trackId===t).map(c=>[c.start,c.duration,c.sourceIn]),[[0,2,0],[2,2,3],[4,13,7]]);assert.equal(T.duration(q),17);T.validate(q);});
test('ripple affects crossing backgrounds and markers',()=>{let p=fixture();p=T.addTrack(p,'video');p=T.addMediaClip(p,'bg','V2',0);p.markers=[{id:'m',time:10,label:'M'}];const q=T.removeRanges(p,[[2,4],[6,8]],{ripple:true});assert.equal(T.duration(q),16);assert.equal(q.markers[0].time,6);assert.equal(q.clips.filter(c=>c.trackId==='V2').reduce((n,c)=>n+c.duration,0),16);T.validate(q);});
test('lock protects linked audio on every core edit',()=>{const p=fixture(),id=p.clips[0].id;p.tracks.find(t=>t.id==='A1').locked=true;for(const fn of [()=>T.splitClips(p,id,3),()=>T.deleteClips(p,id),()=>T.moveClip(p,id,'V1',1),()=>T.removeRanges(p,[[2,3]]),()=>T.resizeClip(p,id,'right',19,false)])assert.throws(fn,/Unlock/);});
test('gap-only ripple with unaffected locked clip is permitted',()=>{let p=fixture();p=T.splitClips(p,p.clips[0].id,5);const right=p.clips.find(c=>c.trackId==='V1'&&c.start===5);p=T.moveClip(p,right.id,'V1',7);p=T.addTrack(p,'video');p=T.addMediaClip(p,'bg','V2',0);p.clips.find(c=>c.trackId==='V2').duration=1;p.tracks.find(t=>t.id==='V2').locked=true;const q=T.removeRanges(p,[[5,7]]);T.validate(q);assert.equal(q.clips.find(c=>c.trackId==='V2').duration,1);});
test('one-frame segment is preserved and source timing is exact',()=>{const p=fixture();const q=T.removeRanges(p,[[1,2],[2+1/30,3]]);assert(q.clips.some(c=>Math.abs(c.duration-1/30)<T.EPS));T.validate(q);});
test('ripple right extension shifts following paired clips together',()=>{let p=fixture();p=T.splitClips(p,p.clips[0].id,5);const c=p.clips.find(c=>c.trackId==='V1'&&c.start===0);const q=T.resizeClip(p,c.id,'right',6,true);assert.deepEqual(q.clips.filter(c=>c.trackId==='V1').map(c=>[c.start,c.duration]),[[0,6],[6,15]]);T.validate(q);});
test('new audio track is allocated when A1 is occupied',()=>{let p=fixture();p=T.addTrack(p,'video');p=T.addMediaClip(p,'v','V2',0);assert(p.tracks.some(t=>t.id==='A2'));T.validate(p);});
test('invalid saved projects are rejected',()=>{const p=fixture();p.clips[0].sourceIn=NaN;assert.throws(()=>T.validate(p),/Invalid/);});
