import test from 'node:test';import assert from 'node:assert/strict';
import {build} from 'esbuild';import {createRequire} from 'node:module';import {readFile} from 'node:fs/promises';import vm from 'node:vm';
import React from 'react';import {renderToStaticMarkup} from 'react-dom/server';
import {emptyProject} from '../src/timeline.js';import {newerVersion,releaseUrl} from '../src/update-check.js';
const require=createRequire(import.meta.url);
async function component(file){const result=await build({entryPoints:[file],bundle:true,write:false,platform:'node',format:'cjs',external:['react','react-dom'],logLevel:'silent'});const mod={exports:{}};vm.runInNewContext(result.outputFiles[0].text,{module:mod,exports:mod.exports,require,structuredClone,console,Buffer,Uint8Array,DataView,ArrayBuffer});return mod.exports;}
test('Creator UI renders simple choices, scoped application and existing import/export controls',async()=>{const {default:Panel}=await component('src/CreatorPanel.jsx');const html=renderToStaticMarkup(React.createElement(Panel,{project:emptyProject(),selectedIds:[],commit:()=>{},fail:()=>{},seek:()=>{}}));for(const label of ['Creator Style','Story mix','Close up','Slow zoom','Selected clips','Main cut track','Save style','Import','Attached sound']){assert(html.includes(label),label);}assert(html.includes('<details>'));});
test('Style inspector retains advanced controls and manual framing lock',async()=>{const {StyleClipControls}=await component('src/CreatorPanel.jsx');const pose={scale:100,x:0,y:0};const html=renderToStaticMarkup(React.createElement(StyleClipControls,{clip:{id:'s',fx:{scene:{from:pose,to:pose}},styleLocked:true},changeFx:()=>{},commit:()=>{}}));assert(html.includes('Fine-tune'));assert(html.includes('Keep this framing'));assert(html.includes('checked'));});
test('Help modal renders version and navigation without network',async()=>{const {default:Help}=await component('src/HelpPanel.jsx');const html=renderToStaticMarkup(React.createElement(Help,{onClose:()=>{},diagnostics:{}}));for(const label of ['0.4.9','Privacy','Licences','Updates','Download diagnostics','Your first edit'])assert(html.includes(label));});
test('release checks compare numeric versions and reject insecure addresses',()=>{assert(newerVersion('0.4.10','0.4.9'));assert(!newerVersion('0.4.9','0.4.9'));assert(!newerVersion('0.3.9','0.4.9'));assert.throws(()=>newerVersion('bad','0.4.9'));assert.equal(releaseUrl(null),null);assert.throws(()=>releaseUrl('http://example.com'));assert.throws(()=>releaseUrl('https://user:pass@example.com'));});
test('desktop package includes all new runtime modules and version numbers agree',async()=>{const pkg=JSON.parse(await readFile('package.json','utf8')),lock=JSON.parse(await readFile('package-lock.json','utf8'));assert.equal(pkg.version,'0.4.9');assert.equal(lock.version,pkg.version);assert.equal(lock.packages[''].version,pkg.version);for(const file of ['desktop-power.cjs','src/media-service.js','src/update-check.js','release-config.json'])assert(pkg.build.files.includes(file),file);const main=await readFile('src/main.jsx','utf8');assert(main.includes('onClick={()=>exportVideo()}'));assert(!main.includes('direct=!forceFallback&&!!'));});
