// Simulated DOM integration. GPU, green sampling, native reconnect and analysis are mocks.
import test from 'node:test';import assert from 'node:assert/strict';
import {build} from 'esbuild';import {readFile} from 'node:fs/promises';
import {JSDOM,VirtualConsole} from 'jsdom';import {IDBFactory} from 'fake-indexeddb';
import * as T from '../src/timeline.js';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function until(check){for(let n=0;n<200;n++){if(check())return;await sleep(20);}throw Error('Workflow condition timed out');}
test('Styles, cut transition picker, track volume and Auto Edit save-copy flow work together',async()=>{
 let p=T.emptyProject();p.name='Original';p.media=[{id:'main',type:'video',name:'Main.mp4',duration:10},{id:'bg',type:'image',name:'Street.png',duration:10},{id:'music',type:'audio',name:'Music.wav',duration:10},{id:'logo',type:'image',name:'Logo.png',duration:10}].map(m=>({...m,sourcePath:'/mock/'+m.name,size:100}));p=T.addMediaClip(p,'main','V1',0);p=T.splitClips(p,p.clips[0].id,5);
 const db=new IDBFactory();await new Promise((resolve,reject)=>{const r=db.open('rancut-projects',2);r.onupgradeneeded=()=>{r.result.createObjectStore('catalog');r.result.createObjectStore('projects');};r.onsuccess=()=>{const tx=r.result.transaction('catalog','readwrite');tx.objectStore('catalog').put({id:'original',name:'Original',project:p,backups:[],createdAt:1,updatedAt:1},'original');tx.oncomplete=()=>{r.result.close();resolve();};tx.onerror=()=>reject(tx.error);};});
 const bundled=await build({entryPoints:['src/main.jsx'],bundle:true,write:false,outdir:'unused',format:'iife',logLevel:'silent',define:{'process.env.NODE_ENV':'"production"'},plugins:[{name:'mock-platform',setup(b){b.onLoad({filter:/renderer\.js$/},()=>({loader:'js',contents:'export class Renderer {gpuInfo(){return {renderer:"Mock"}} pause(){} resetMedia(){} dispose(){} draw(){return Promise.resolve()} meter(){return -60}}'}));b.onLoad({filter:/auto-edit\.js$/},async a=>({loader:'js',contents:(await readFile(a.path,'utf8')).split('export async function sampleGreen')[0]+'export async function sampleGreen(){return "#147014";}'}));}}]});
 const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const dom=new JSDOM('<div id="root"></div>',{url:'http://127.0.0.1:5174',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc});const w=dom.window,d=w.document;
 const analysis={levels:Array.from({length:200},(_,i)=>i>=60&&i<100?-65:-25),windowSec:.05,peaks:[-.1,.1],peakStep:.005};
 Object.assign(w,{indexedDB:db,structuredClone,TextEncoder,TextDecoder,AbortSignal,ResizeObserver:class{observe(){}disconnect(){}},confirm:()=>true,fetch:async url=>({ok:true,json:async()=>String(url).includes('analyse')?analysis:{directory:'/exports',ffmpeg:true}}),rancut:{desktop:true,onPrepareClose:()=>()=>{},onSuspend:()=>()=>{},reconnect:async items=>items.map(m=>({mediaId:m.id,id:'server_'+m.id,url:'http://127.0.0.1:5174/mock/'+m.id}))}});
 w.HTMLCanvasElement.prototype.getContext=()=>({drawImage(){},scale(){},clearRect(){},beginPath(){},moveTo(){},lineTo(){},stroke(){}});w.HTMLCanvasElement.prototype.toDataURL=()=>'';w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};w.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');};w.URL.createObjectURL=()=> 'blob:mock';w.URL.revokeObjectURL=()=>{};
 const click=(text,root=d)=>{const b=[...root.querySelectorAll('button')].find(b=>b.textContent.trim()===text);assert(b,'Missing '+text);assert(!b.disabled,'Disabled '+text);b.click();};
 const set=(label,value)=>{const el=d.querySelector('[aria-label="'+label+'"]');assert(el,label);const proto=el.tagName==='SELECT'?w.HTMLSelectElement.prototype:w.HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(el,value);el.dispatchEvent(new w.Event(el.tagName==='SELECT'?'change':'input',{bubbles:true}));};
 try{
 w.eval(bundled.outputFiles.find(f=>f.path.endsWith('.js')).text);await until(()=>d.querySelector('.projectCover'));d.querySelector('.projectCover').click();await until(()=>!d.querySelector('.projectHome')&&d.querySelector('.clipBox'));await sleep(100);
 click('Styles');await until(()=>d.querySelectorAll('.stylePreset').length===2);click('Edit',d.querySelector('.stylePreset'));await until(()=>d.querySelector('.styleEditor'));click('Reset to default');await sleep(20);click('Save style');await until(()=>!d.querySelector('.styleEditor'));click('Apply',d.querySelector('.stylePreset'));await until(()=>d.querySelectorAll('.clipBox.adjustment').length===2);
 d.querySelector('.cutTarget').click();await until(()=>d.querySelector('.workflowDialog[open]'));assert(d.querySelector('.workflowDialog').textContent.includes('This cut only'));set('Transition scope','all');d.querySelector('[aria-label="Include transition sound"]').click();await sleep(30);click('Apply transition');await until(()=>!d.querySelector('.workflowDialog'));assert.equal(d.querySelectorAll('.cutTarget.hasTransition').length,1);assert.equal(d.querySelectorAll('.trackLabel').length,3);
 d.querySelector('[title="Adjust full-track volume"]').click();await until(()=>d.querySelector('[aria-label="Scoped gain"]'));set('Scoped gain','5');await sleep(20);click('Apply volume');await until(()=>d.querySelector('.trackName[title="Adjust full-track volume"]').textContent.includes('5 dB'));click('Done',d.querySelector('dialog'));await until(()=>!d.querySelector('dialog'));
 click('✦ Auto Edit');await until(()=>d.querySelector('.autoWizard'));click('Next');await sleep(20);set('Background','bg');set('Logo image','logo');set('Auto Edit style','dynamic');set('Auto Edit transition','whoosh');await sleep(20);click('Next');await sleep(20);set('Background music','music');await sleep(20);click('Next');await sleep(20);click('Analyse & prepare edit');await until(()=>d.querySelector('.autoSummary'));assert(d.querySelector('.autoSummary').textContent.includes('2 main clips'));click('Generate editable project copy');await until(()=>!d.querySelector('.autoWizard'));assert(d.querySelector('.saveBadge').textContent.includes('Auto Edit'));assert.equal(d.querySelectorAll('.trackLabel').length,6);d.querySelector('[title="Remove track (keeps original media)"]').click();await until(()=>d.querySelectorAll('.trackLabel').length===5);d.querySelector('[title="Undo"]').click();await until(()=>d.querySelectorAll('.trackLabel').length===6);
 click('Projects');await until(()=>d.querySelectorAll('.projectCard').length===2);assert(d.querySelector('.projectHome').textContent.includes('Original — Auto Edit'));assert.deepEqual(errors,[]);
 }catch(e){throw Error(e.message+'; errors='+JSON.stringify(errors)+'; ui='+d.body.textContent.slice(-2000));}finally{dom.window.close();}
});
