import React,{useState,useRef,useEffect} from 'react';
import {setAudioGain} from './creator-workflow.js';
export default function AudioControls({project,clipId,selectedIds,commit,trackId:initialTrack}){
 const c=project.clips.find(c=>c.id===clipId),audio=project.tracks.find(t=>t.id===c?.trackId)?.type==='audio'?c:project.clips.find(a=>a.id===c?.linkedId),[scope,setScope]=useState(initialTrack?'track':'clip'),[trackId,setTrackId]=useState(initialTrack||audio?.trackId||''),[db,setDb]=useState(initialTrack?(project.tracks.find(t=>t.id===initialTrack)?.gainDb||0):(audio?.fx?.gainDb||0)),[error,setError]=useState('');const active=project.tracks.some(t=>t.id===trackId&&t.type==='audio')?trackId:audio?.trackId||project.tracks.find(t=>t.type==='audio')?.id;
 return <div className="audioScope"><h4>Audio volume</h4><label>Apply volume to<select aria-label="Audio volume scope" value={scope} onChange={e=>{setScope(e.target.value);setDb(e.target.value==='track'?(project.tracks.find(t=>t.id===active)?.gainDb||0):(audio?.fx?.gainDb||0));}}><option value="clip">This clip</option><option value="selected">Selected clips</option><option value="track">Full track — all cuts</option></select></label>{scope==='track'&&<><label>Track<select aria-label="Audio master track" value={active||''} onChange={e=>{setTrackId(e.target.value);setDb(project.tracks.find(t=>t.id===e.target.value)?.gainDb||0);}}>{project.tracks.filter(t=>t.type==='audio').map(t=><option key={t.id} value={t.id}>{t.name||t.id} · {t.gainDb||0} dB</option>)}</select></label><p>Track gain adds to each clip’s gain; combined gain is limited to −60…+12 dB. No need to select all cuts.</p></>}<label>Gain (dB)<input aria-label="Scoped gain" type="number" min="-60" max="12" step=".1" value={db} onChange={e=>setDb(+e.target.value)}/></label><div><button onClick={()=>{try{const q=setAudioGain(project,{scope,clipId,ids:selectedIds,trackId:active,db});commit(q,'Audio volume updated');setError('');}catch(e){setError(e.message);}}}>Apply volume</button><button onClick={()=>setDb(0)}>Set 0 dB</button></div>{error&&<p role="alert">{error}</p>}</div>;
}

export function TrackAudioDialog({project,trackId,commit,onClose}){
 const ref=useRef();useEffect(()=>{ref.current.showModal();return()=>ref.current?.close();},[]);
 return <dialog className="workflowDialog trackAudioDialog" ref={ref} onCancel={onClose}><header><h2>Track audio</h2><button onClick={onClose}>×</button></header><div className="workflowBody"><AudioControls project={project} selectedIds={[]} trackId={trackId} commit={commit}/></div><footer><button onClick={onClose}>Done</button></footer></dialog>;
}
