import React,{useState,useRef,useEffect} from 'react';
import * as T from './timeline.js';
import FramingWorkspace from './FramingWorkspace.jsx';
import {defaultFraming} from './framing.js';
export default function AutoEditWizard({project,media,onImport,onPreview,onApply,onClose,onFrame,onSceneFrame}){
 const [step,setStep]=useState(0),[o,setO]=useState({mainId:project.media.find(m=>m.type==='video')?.id||'',voiceId:'',green:true,normalize:true,backgroundId:'',bgmId:'',logoId:'',style:'simple',trim:true,clean:false,allShort:false,maxDuration:2,threshold:-38,minPause:.55,padding:.12,transition:'none',sound:false,bgmDb:-24,duck:true,includeLogo:false,crop:null,framing:project.creatorFraming||defaultFraming(),subject:null,frameTime:0,baseScale:108}),[draft,setDraft]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [previewWidth,setPreviewWidth]=useState(60);const layout=useRef();
 const resizePanels=e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);};
 const moveDivider=e=>{if(!e.currentTarget.hasPointerCapture(e.pointerId))return;const r=layout.current.getBoundingClientRect();setPreviewWidth(T.clamp((e.clientX-r.left)/r.width*100,40,70));};
 const dialog=useRef(),input=useRef(),frameRequest=useRef(0);useEffect(()=>{dialog.current.showModal();return()=>{frameRequest.current++;dialog.current?.close();};},[]);
 const change=(k,v)=>{setO(x=>({...x,[k]:v,...(k==='mainId'?{crop:null,framing:defaultFraming(),frameTime:0}:{} )}));setDraft(null);setError('');};
 const select=(key,label,filter,none='Skip')=><label>{label}<select aria-label={label} value={o[key]} onChange={e=>change(key,e.target.value)}><option value="">{none}</option>{project.media.filter(filter).map(m=><option key={m.id} value={m.id}>{m.name}{!media.find(x=>x.id===m.id)?.url?' — missing':''}</option>)}</select></label>;
 const check=(key,label)=><label className="check"><input type="checkbox" checked={o[key]} onChange={e=>change(key,e.target.checked)}/>{label}</label>;
 const number=(key,label,min,max,step=.1)=><label>{label}<input aria-label={label} type="number" min={min} max={max} step={step} value={o[key]} onChange={e=>change(key,+e.target.value)}/></label>;
 const preview=async()=>{setBusy(true);setError('');try{setDraft(await onPreview(o));}catch(e){setError(e.message);}finally{setBusy(false);}};
 const apply=async()=>{setBusy(true);setError('');try{await onApply(draft);onClose();}catch(e){setError(e.message);}finally{setBusy(false);}};
 return <dialog ref={dialog} className="workflowDialog autoWizard creatorWorkspace" onCancel={e=>{if(busy)e.preventDefault();else onClose();}}><header><div><h2>Auto Edit</h2><p>A guided starting edit. Your current project stays safe.</p></div><div><button disabled={busy} aria-label="Close Auto Edit" onClick={onClose}>×</button></div></header><nav>{['Sources','Crop & framing','Look','Sound & cuts','Review'].map((s,i)=><button disabled={busy} key={s} className={step===i?'chosen':''} onClick={()=>setStep(i)}>{i+1}. {s}</button>)}</nav>
 <div className="autoColumns" ref={layout} style={{gridTemplateColumns:previewWidth+'% 8px minmax(0,1fr)'}}><div className="autoPreview"><FramingWorkspace value={o.framing} onChange={v=>change('framing',v)} crop={o.crop||{}} onCrop={v=>change('crop',v)} disabled={busy} mediaKey={o.mainId} sourceKey={JSON.stringify([o.mainId,o.backgroundId,o.green,o.crop])} duration={project.media.find(m=>m.id===o.mainId)?.duration||0} initialTime={o.frameTime} loadFrame={at=>onSceneFrame?onSceneFrame(o,at):onFrame?.(o.mainId,at)} style={o.style==='none'?'None':o.style==='simple'?'Simple':'Dynamic'}/></div><div className="autoDivider" role="separator" aria-label="Resize preview and controls" tabIndex="0" onPointerDown={resizePanels} onPointerMove={moveDivider} onKeyDown={e=>{if(e.key==='ArrowLeft')setPreviewWidth(v=>Math.max(40,v-2));if(e.key==='ArrowRight')setPreviewWidth(v=>Math.min(70,v+2));}}/><div className="workflowBody autoControls"><fieldset disabled={busy}>
 {step===0&&<><label>Video type<select aria-label="Video type" value={o.green?'green':'regular'} onChange={e=>change('green',e.target.value==='green')}><option value="green">Green-screen video</option><option value="regular">Regular video</option></select></label>{select('mainId','Main video',m=>m.type==='video','Choose a video')}{select('voiceId','Voice audio',m=>m.type==='audio'||m.type==='video','Use main video audio')}<p>Separate voice recording must start in sync at 0:00 and cover the video. Background video audio is not used.</p>{check('normalize','Auto-adjust voice volume (peak-safe starting level)')}<button onClick={()=>input.current.click()}>Import video / audio / images</button><input type="file" ref={input} hidden multiple accept="video/*,audio/*,image/*" onChange={async e=>{setBusy(true);try{await onImport([...e.target.files]);}catch(e){setError(e.message);}finally{setBusy(false);e.target.value='';}}}/></>}
 {step===1&&<><h3>Set your camera framing</h3><p>Clean edges is a separate source mask. Drag the visible box or use its sliders.</p><p>Normal base and Max close-up are locked 16:9. Put the close-up around your head and chest, leaving headroom. It stays inside the base.</p><p>The small live output shows the final framing. In Style preview, choose a shot and play its movement. Bottom cropping is allowed.</p><p>Fit shows the full composition. Fill trims letterboxing. Reset restores the active frame only.</p></>}
 {step===2&&<>{o.green&&select('backgroundId','Background',m=>m.type==='video'||m.type==='image')}{select('logoId','Logo image',m=>m.type==='image')}<label>Creator Style<select aria-label="Auto Edit style" value={o.style} onChange={e=>change('style',e.target.value)}><option value="none">Skip</option><option value="simple">Simple — gentle framing</option><option value="dynamic">Dynamic — stronger changes</option></select></label>{check('includeLogo','Include logo in scene zoom (otherwise fixed)')}<p>Styles move person + background together. Logo starts at the upper-right; all positions remain editable.</p><label>Transitions<select aria-label="Auto Edit transition" value={o.transition} onChange={e=>change('transition',e.target.value)}>{['none','paper','whoosh','shutter','glitch','fade'].map(k=><option key={k} value={k}>{k==='none'?'Skip transitions':k}</option>)}</select></label>{o.transition!=='none'&&check('sound','Include matching transition sounds')}</>}
 {step===3&&<>{select('bgmId','Background music',m=>m.type==='audio'||m.type==='video')}{o.bgmId&&<>{number('bgmDb','BGM level (dB)',-60,0,1)}{check('duck','Lower BGM another 10 dB while voice clips are active')}</>}{check('trim','Automatically remove pauses')}{o.trim&&<>{number('threshold','Silence threshold (dB)',-65,-15,1)}{number('minPause','Minimum pause (seconds)',.1,10)}{number('padding','Speech padding (seconds)',0,1,.01)}</>}{check('clean','Clean short leftovers after cutting')}{o.clean&&<>{number('maxDuration','Maximum leftover length (seconds)',.2,3)}{check('allShort','Aggressive: remove ALL short clips, including possible speech')}<p>Default removes mostly quiet short pieces. This is not cough recognition. Review the resulting cuts before export.</p></>}</>}
 {step===4&&<><h3>Review before generating</h3><p>{o.green?'Green screen':'Regular'} · {o.style} Style · {o.transition} transitions · transition sound {o.sound&&o.transition!=='none'?'on':'off'}</p><p>Crop {o.crop?'on':'off'} · saved 16:9 base / close-up · Voice adjustment {o.normalize?'on':'off'} · Pause removal {o.trim?'on':'off'} · Leftover cleanup {o.clean?'on':'off'}</p><p>Video backgrounds and BGM repeat to cover the edit. Nothing is uploaded. Preview planning may wait for local audio analysis.</p><button disabled={!o.mainId} onClick={preview}>Analyse & prepare edit</button>{draft&&<div className="autoSummary"><b>{draft.clips.filter(c=>c.trackId==='V2').length} main clips · {T.duration(draft).toFixed(1)} seconds</b><p>A new project copy will be saved. Original project, source files and media remain untouched.</p><details><summary>Review main cut source ranges</summary>{draft.clips.filter(c=>c.trackId==='V2').map(c=><p key={c.id}>Source {c.sourceIn.toFixed(2)}–{(c.sourceIn+c.duration).toFixed(2)}s → timeline {c.start.toFixed(2)}s</p>)}</details></div>}</>}
 </fieldset>{busy&&<p role="status">Working locally… please wait.</p>}{error&&<p className="exportError" role="alert">{error}</p>}</div></div><footer><button disabled={busy} onClick={()=>step?setStep(step-1):onClose()}>{step?'Back':'Cancel'}</button>{step<4?<button disabled={busy||!o.mainId} onClick={()=>setStep(step+1)}>Next</button>:<button className="primary" disabled={busy||!draft} onClick={apply}>Generate editable project copy</button>}</footer></dialog>;
}
