import * as T from './timeline.js';
import * as C from './creator.js';
import {creatorStyles,silenceRanges,shortLeftovers,voiceGain,applyTransitions} from './creator-workflow.js';
export function buildAutoEdit(source,options,analysis){
 for(const [key,min,max] of [['threshold',-65,-15],['minPause',.1,10],['padding',0,1],['maxDuration',.2,3],['bgmDb',-60,0],['soundDb',-60,6]])if(options[key]!==undefined&&(!Number.isFinite(options[key])||options[key]<min||options[key]>max))throw Error('Invalid '+key+' setting.');
 const media=id=>source.media.find(m=>m.id===id),main=media(options.mainId),voice=media(options.voiceId||options.mainId);if(main?.type!=='video')throw Error('Choose the main video.');if(!voice||voice.type==='image')throw Error('Choose a voice source.');
 let p={...T.emptyProject(),fps:source.fps,width:source.width,height:source.height,name:(source.name||'Project')+' — Auto Edit',media:structuredClone(source.media),tracks:[{id:'V2',type:'video',name:'Main video'},{id:'V1',type:'video',name:'Background'},{id:'A1',type:'audio',name:'Voice',gainDb:options.normalize?voiceGain(analysis):0}]};
 const duration=Math.floor(main.duration*p.fps)/p.fps;if(duration<1/p.fps)throw Error('Main video is too short.');if(voice.duration+1/p.fps<duration)throw Error('Voice source is shorter than the main video. Use the embedded audio or a matching full-length recording.');
 const v={id:T.uid(),mediaId:main.id,name:main.name,trackId:'V2',start:0,duration,sourceIn:0,fx:{...T.fxDefault(),crop:{...T.fxDefault().crop,...(options.crop||{})}},linkedId:null};
 if(options.subject)v.fx.subject=structuredClone(options.subject);
 if(options.green){if(!options.key)throw Error('Green-screen sampling failed. Choose Regular or check the footage.');v.fx.chroma={...v.fx.chroma,enabled:true,key:options.key};}
 const a={...structuredClone(v),id:T.uid(),mediaId:voice.id,name:voice.name,trackId:'A1',fx:T.fxDefault()};if(voice.id===main.id){v.linkedId=a.id;a.linkedId=v.id;}p.clips=[v,a];
 if(options.trim){const ranges=silenceRanges(a,analysis,{threshold:options.threshold??-62,minPause:options.minPause??.55,padding:options.padding??.12,fps:p.fps});p=T.removeRanges(p,ranges,{ripple:true});}
 if(options.clean){const leftovers=shortLeftovers(p,'A1',()=>analysis,{maxDuration:options.maxDuration??2,threshold:options.cleanupThreshold??-30,allShort:!!options.allShort});if(leftovers.length)p=T.removeRanges(p,leftovers.map(x=>x.range),{ripple:true});}
 const length=T.duration(p);if(!p.clips.some(c=>c.trackId==='V2')||length<1/p.fps)throw Error('These cleanup settings remove the whole video. Reduce cleanup or silence thresholds.');
 const loop=(id,trackId,fx={})=>{const m=media(id);if(!m)return;if(trackId==='V1'&&m.type==='audio')throw Error('Background must be a video or image.');if(trackId==='A2'&&m.type==='image')throw Error('BGM must be audio or video.');const chunk=m.type==='image'?length:Math.floor(m.duration*p.fps)/p.fps;if(chunk<1/p.fps)throw Error('Background/music source is too short.');if(Math.ceil(length/chunk)>1000)throw Error('Choose a longer background/music source.');for(let start=0;start<length-T.EPS;start=T.quant(start+chunk,p.fps))p.clips.push({id:T.uid(),mediaId:m.id,name:m.name,trackId,start,duration:Math.min(chunk,length-start),sourceIn:0,linkedId:null,fx:{...T.fxDefault(),...fx}});};
 loop(options.backgroundId,'V1');
 if(options.bgmId){p.tracks.push({id:'A2',type:'audio',name:'BGM',gainDb:options.bgmDb??-24,duckAgainst:options.duck?'A1':null,duckDb:-10});loop(options.bgmId,'A2');}
 if(options.logoId){const logo=media(options.logoId);if(logo?.type!=='image')throw Error('Logo must be an image.');p.tracks.unshift({id:'V3',type:'video',name:'Logo',fixedOverlay:true});loop(options.logoId,'V3',{transform:{scale:18,x:96,y:96,opacity:100}});}
 if(options.style&&options.style!=='none')p=C.applyStyle(p,'V2',creatorStyles[options.style==='dynamic'?1:0],options.seed??42,{includeLogo:!!options.includeLogo,subject:options.subject,baseScale:options.baseScale??108,framing:options.framing});
 if(options.framing&&(!options.style||options.style==='none'))p=C.applyStyle(p,'V2',{...creatorStyles[0],name:'Base only',shots:[creatorStyles[0].shots[0]]},0,{framing:options.framing,includeLogo:!!options.includeLogo});
 if(options.transition&&options.transition!=='none'&&C.cutPairs(p,'V2').length)p=applyTransitions(p,{trackId:'V2',preset:{...C.transitionPreset(options.transition),sound:!!options.sound,gainDb:options.soundDb??-16},all:true,replace:true});
 const used=new Set(p.clips.map(c=>c.mediaId));p.media=p.media.filter(m=>used.has(m.id));p.creatorSource='V2';return T.validate(p);
}
export async function sampleGreen(url){const v=document.createElement('video');v.muted=true;v.preload='auto';try{await new Promise((resolve,reject)=>{const timer=setTimeout(()=>done(Error('Green-screen sample timed out.')),15000);const done=e=>{clearTimeout(timer);v.onloadeddata=null;v.onerror=null;e?reject(e):resolve();};v.onloadeddata=()=>done();v.onerror=()=>done(Error('Cannot decode the main video.'));v.src=url;v.load();});const c=document.createElement('canvas');c.width=320;c.height=Math.max(1,Math.round(320*v.videoHeight/v.videoWidth));const ctx=c.getContext('2d');ctx.drawImage(v,0,0,c.width,c.height);const pixels=ctx.getImageData(0,0,c.width,c.height).data,greens=[];for(let i=0;i<pixels.length;i+=16){const [r,g,b]=pixels.slice(i,i+3);if(g>r*1.3&&g>b*1.3&&g>20)greens.push([r,g,b]);}if(greens.length<30)throw Error('No clear green area in the first frame. Use regular mode and key manually.');return '#'+[0,1,2].map(k=>greens.map(rgb=>rgb[k]).sort((a,b)=>a-b)[Math.floor(greens.length/2)].toString(16).padStart(2,'0')).join('');}finally{v.removeAttribute('src');v.load();}}
