import React,{useState,useRef,useEffect} from 'react';
import * as T from './timeline.js';
import FrameDialog from './FrameDialog.jsx';
export default function AutoEditWizard({project,media,onImport,onPreview,onApply,onClose,onFrame}){
 const [step,setStep]=useState(0),[o,setO]=useState({mainId:project.media.find(m=>m.type==='video')?.id||'',voiceId:'',green:true,normalize:true,backgroundId:'',bgmId:'',logoId:'',style:'simple',trim:true,clean:false,allShort:false,maxDuration:2,threshold:-38,minPause:.55,padding:.12,transition:'none',sound:false,bgmDb:-24,duck:true,includeLogo:false,crop:null,subject:null,frameTime:0}),[draft,setDraft]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[expand,setExpand]=useState(false),[frame,setFrame]=useState(null);
 const dialog=useRef(),input=useRef();useEffect(()=>{dialog.current.showModal();return()=>dialog.current?.close();},[]);
 const change=(k,v)=>{setO(x=>({...x,[k]:v}));setDraft(null);setError('');};
 const select=(key,label,filter,none='Skip')=><label>{label}<select aria-label={label} value={o[key]} onChange={e=>change(key,e.target.value)}><option value="">{none}</option>{project.media.filter(filter).map(m=><option key={m.id} value={m.id}>{m.name}{!media.find(x=>x.id===m.id)?.url?' — missing':''}</option>)}</select></label>;
 const check=(key,label)=><label className="check"><input type="checkbox" checked={o[key]} onChange={e=>change(key,e.target.checked)}/>{label}</label>;
 const number=(key,label,min,max,step=.1)=><label>{label}<input aria-label={label} type="number" min={min} max={max} step={step} value={o[key]} onChange={e=>change(key,+e.target.value)}/></label>;
 const preview=async()=>{setBusy(true);setError('');try{setDraft(await onPreview(o));}catch(e){setError(e.message);}finally{setBusy(false);}};
 const apply=async()=>{setBusy(true);setError('');try{await onApply(draft);onClose();}catch(e){setError(e.message);}finally{setBusy(false);}};
 const openFrame=async kind=>{if(!o.mainId){setError('Choose the main video first.');return;}setFrame({kind,image:'',loading:true});try{const image=await onFrame?.(o.mainId,o.frameTime);if(!image)throw Error('Could not decode this preview frame.');setFrame({kind,image,loading:false});}catch(e){setFrame(null);setError(e.message||'Could not decode this preview frame.');}};
 return <>{frame&&<FrameDialog kind={frame.kind} image={frame.image} loading={frame.loading} initial={o[frame.kind]} onClose={()=>setFrame(null)} onApply={v=>{change(frame.kind,v);setFrame(null);}}/>}<dialog ref={dialog} className={'workflowDialog autoWizard '+(expand?'expanded':'')} onCancel={e=>{if(busy)e.preventDefault();else onClose();}}><header><div><h2>Auto Edit</h2><p>A guided starting edit. Your current project stays safe.</p></div><div><button className="expandDialog" title="Expand Auto Edit workspace" onClick={()=>setExpand(v=>!v)}>{expand?'Reduce':'Expand'}</button><button disabled={busy} aria-label="Close Auto Edit" onClick={onClose}>×</button></div></header><nav>{['Sources','Crop & framing','Look','Sound & cuts','Review'].map((s,i)=><button disabled={busy} key={s} className={step===i?'chosen':''} onClick={()=>setStep(i)}>{i+1}. {s}</button>)}</nav>
 <div className="workflowBody"><fieldset disabled={busy}>
 {step===0&&<><label>Video type<select aria-label="Video type" value={o.green?'green':'regular'} onChange={e=>change('green',e.target.value==='green')}><option value="green">Green-screen video</option><option value="regular">Regular video</option></select></label>{select('mainId','Main video',m=>m.type==='video','Choose a video')}{select('voiceId','Voice audio',m=>m.type==='audio'||m.type==='video','Use main video audio')}<p>Separate voice recording must start in sync at 0:00 and cover the video. Background video audio is not used.</p>{check('normalize','Auto-adjust voice volume (peak-safe starting level)')}<button onClick={()=>input.current.click()}>Import video / audio / images</button><input type="file" ref={input} hidden multiple accept="video/*,audio/*,image/*" onChange={async e=>{setBusy(true);try{await onImport([...e.target.files]);}catch(e){setError(e.message);}finally{setBusy(false);e.target.value='';}}}/></>}
 {step===1&&<><p>Optional, but recommended for green-screen footage with a light edge/stand in frame. If the main clip is already under the timeline playhead, that exact frame is used. Otherwise choose a source time below.</p>{number('frameTime','Preview source time (seconds)',0,86400,.01)}<button onClick={()=>openFrame('crop')}>{o.crop?'Edit clean edges':'Clean unwanted picture edges'}</button><button onClick={()=>openFrame('subject')}>{o.subject?'Edit protected subject box':'Protect head/body from Style zooms'}</button>{o.subject&&<p>Protected framing is on. Dynamic Style zooms will stay conservative.</p>}</>}
 {step===2&&<>{o.green&&select('backgroundId','Background',m=>m.type==='video'||m.type==='image')}{select('logoId','Logo image',m=>m.type==='image')}<label>Creator Style<select aria-label="Auto Edit style" value={o.style} onChange={e=>change('style',e.target.value)}><option value="none">Skip</option><option value="simple">Simple — gentle framing</option><option value="dynamic">Dynamic — stronger changes</option></select></label>{check('includeLogo','Include logo in scene zoom (otherwise fixed)')}<p>Styles move person + background together. Logo starts at the upper-right; all positions remain editable.</p><label>Transitions<select aria-label="Auto Edit transition" value={o.transition} onChange={e=>change('transition',e.target.value)}>{['none','paper','whoosh','shutter','glitch','fade'].map(k=><option key={k} value={k}>{k==='none'?'Skip transitions':k}</option>)}</select></label>{o.transition!=='none'&&check('sound','Include matching transition sounds')}</>}
 {step===3&&<>{select('bgmId','Background music',m=>m.type==='audio'||m.type==='video')}{o.bgmId&&<>{number('bgmDb','BGM level (dB)',-60,0,1)}{check('duck','Lower BGM another 10 dB while voice clips are active')}</>}{check('trim','Automatically remove pauses')}{o.trim&&<>{number('threshold','Silence threshold (dB)',-65,-15,1)}{number('minPause','Minimum pause (seconds)',.1,10)}{number('padding','Speech padding (seconds)',0,1,.01)}</>}{check('clean','Clean short leftovers after cutting')}{o.clean&&<>{number('maxDuration','Maximum leftover length (seconds)',.2,3)}{check('allShort','Aggressive: remove ALL short clips, including possible speech')}<p>Default removes mostly quiet short pieces. This is not cough recognition. Review the resulting cuts before export.</p></>}</>}
 {step===4&&<><h3>Review before generating</h3><p>{o.green?'Green screen':'Regular'} · {o.style} Style · {o.transition} transitions · transition sound {o.sound&&o.transition!=='none'?'on':'off'}</p><p>Crop {o.crop?'on':'off'} · protected subject {o.subject?'on':'off'} · Voice adjustment {o.normalize?'on':'off'} · Pause removal {o.trim?'on':'off'} · Leftover cleanup {o.clean?'on':'off'}</p><p>Video backgrounds and BGM repeat to cover the edit. Nothing is uploaded. Preview planning may wait for local audio analysis.</p><button disabled={!o.mainId} onClick={preview}>Analyse & prepare edit</button>{draft&&<div className="autoSummary"><b>{draft.clips.filter(c=>c.trackId==='V2').length} main clips · {T.duration(draft).toFixed(1)} seconds</b><p>A new project copy will be saved. Original project, source files and media remain untouched.</p><details><summary>Review main cut source ranges</summary>{draft.clips.filter(c=>c.trackId==='V2').map(c=><p key={c.id}>Source {c.sourceIn.toFixed(2)}–{(c.sourceIn+c.duration).toFixed(2)}s → timeline {c.start.toFixed(2)}s</p>)}</details></div>}</>}
 </fieldset>{busy&&<p role="status">Working locally… please wait.</p>}{error&&<p className="exportError" role="alert">{error}</p>}</div><footer><button disabled={busy} onClick={()=>step?setStep(step-1):onClose()}>{step?'Back':'Cancel'}</button>{step<4?<button disabled={busy||!o.mainId} onClick={()=>setStep(step+1)}>Next</button>:<button className="primary" disabled={busy||!draft} onClick={apply}>Generate editable project copy</button>}</footer></dialog></>;
}
