import React,{useEffect,useRef,useState} from 'react';
import * as C from './creator.js';
import {creatorStyles} from './creator-workflow.js';
const stamp=t=>`${Math.floor(t/60)}:${(t%60).toFixed(2).padStart(5,'0')}`;
function download(value,name){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name.replace(/[^a-zA-Z0-9_-]/g,'_')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function saved(key){try{const values=JSON.parse(localStorage.getItem(key)||'[]');if(!Array.isArray(values))return [];return values.flatMap(v=>{try{return [key.includes('styles')?C.validateStyle(v):C.validateTransition(v)];}catch{return [];}});}catch{return [];}}
export function StyleClipControls({clip,changeFx,commit}){
 const m=clip.fx.scene;
 return <div className="creatorCard"><b>Scene motion · person + background</b><p>Choose a framing below. Manual edits are kept when you regenerate.</p><div className="creatorButtons">{C.builtInStyle.shots.map(shot=><button key={shot.name} onClick={()=>{changeFx(clip.id,'scene','from',C.baseStylePose(shot.from,m.subject,m.baseScale??108));changeFx(clip.id,'scene','to',C.baseStylePose(shot.to,m.subject,m.baseScale??108));}}>{shot.name}</button>)}</div><details><summary>Fine-tune start / end framing</summary>{['from','to'].map(edge=><fieldset key={edge}><legend>{edge==='from'?'Start':'End'} framing</legend>{['scale','x','y'].map(k=><label key={k}>{k}<input aria-label={`${edge} scene ${k}`} type="number" min={k==='scale'?100:-30} max={k==='scale'?180:30} value={m[edge][k]} onChange={e=>changeFx(clip.id,'scene',edge,{...m[edge],[k]:+e.target.value})}/></label>)}</fieldset>)}</details><label><input type="checkbox" checked={!!clip.styleLocked} onChange={e=>commit(p=>({...p,clips:p.clips.map(c=>c.id===clip.id?{...c,styleLocked:e.target.checked}:c)}),'Style segment lock updated')}/> Keep this framing on regenerate</label></div>;
}

export default function CreatorPanel({project,clip,selectedIds=[],commit,fail,seek}){
 const videos=project.tracks.filter(t=>t.type==='video'),[track,setTrack]=useState(project.creatorSource||videos.find(t=>t.id===clip?.trackId)?.id||videos[0]?.id||''),[styles,setStyles]=useState(()=>saved('rancut-styles-v1')),[editing,setEditing]=useState(null),[scope,setScope]=useState('all'),[includeLogo,setIncludeLogo]=useState(false),[baseScale,setBaseScale]=useState(108),[error,setError]=useState('');const input=useRef();
 const activeTrack=videos.some(t=>t.id===track)?track:videos[0]?.id||'';
 const allStyles=[...creatorStyles,...styles.filter(s=>!creatorStyles.some(b=>b.name===s.name))];
 const run=fn=>{try{setError('');fn();}catch(e){setError(e.message);}};
 const apply=style=>run(()=>{const ids=scope==='selected'?project.clips.filter(c=>c.trackId===activeTrack&&(c.id===clip?.id||c.linkedId===clip?.id||selectedIds.includes(c.id))).map(c=>c.id):undefined;if(ids&&!ids.length)throw Error('Select a clip on the main video track.');const subject=project.clips.find(c=>c.trackId===activeTrack&&(c.id===clip?.id||selectedIds.includes(c.id)))?.fx?.subject;commit(p=>C.applyStyle(p,activeTrack,style,Date.now(),{ids,includeLogo,subject,baseScale}),'Creator Style applied');});
 const store=()=>run(()=>{const value=C.validateStyle(editing),next=[...styles.filter(s=>s.name!==value.name),value].slice(-20);localStorage.setItem('rancut-styles-v1',JSON.stringify(next));setStyles(next);setEditing(null);});
 const presets=allStyles.map(s=>styles.find(x=>x.name===s.name)||s);
 return <div className="creatorPanel"><div className="creatorCard"><h3>Creator Styles</h3><p>Person + background move together. Transitions are separate: click + on a cut.</p><label>Base scene zoom (%)<input aria-label="Base scene zoom" type="number" min="100" max="130" value={baseScale} onChange={e=>setBaseScale(+e.target.value)}/></label><p>Normal starts at this zoom; other shots zoom closer. Protected framing can limit zoom. Reapply a Style to update existing unlocked segments.</p><label>Main cut track<select aria-label="Style main track" value={activeTrack} onChange={e=>setTrack(e.target.value)}>{videos.map(t=><option key={t.id} value={t.id}>{t.name||t.id}</option>)}</select></label><label>Apply to<select aria-label="Style scope" value={scope} onChange={e=>setScope(e.target.value)}><option value="all">Full timeline — main track cuts</option><option value="selected">Selected clip only</option></select></label><label><input type="checkbox" checked={includeLogo} onChange={e=>setIncludeLogo(e.target.checked)}/> Include fixed logo tracks in zoom</label>
 <div className="stylePresetList">{presets.map((style,i)=><article className={'stylePreset '+(i===1?'dynamic':'')} key={style.name}><div className="styleIllustration"><i/><i/><i/></div><b>{style.name}</b><p>{i===0?'Gentle zooms and small position changes':i===1?'Stronger zooms and moving left/right framing':style.shots.length+' framing choices'}</p><div><button className="primary" onClick={()=>apply(style)}>Apply</button><button onClick={()=>setEditing(structuredClone(style))}>Edit</button></div></article>)}</div>
 <div className="creatorButtons"><button onClick={()=>input.current.click()}>Import style</button><button onClick={()=>run(()=>setEditing(C.captureStyle(project,'My Style')))}>Capture edited Style</button></div><input ref={input} hidden type="file" accept=".json" onChange={async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>2000000)throw Error('Preset too large.');setEditing(C.validateStyle(JSON.parse(await f.text())));}catch(e){setError(e.message);}finally{e.target.value='';}}}/>
 {editing&&<div className="styleEditor"><h4>Edit {editing.name}</h4><label>Preset name<input maxLength={80} value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><p>Scale: 100–180%. Position: −30 to +30. Reset restores the original built-in preset.</p>{editing.shots.map((shot,i)=><details key={i}><summary>{shot.name}</summary>{['from','to'].map(edge=><fieldset key={edge}><legend>{edge==='from'?'Start':'End'}</legend>{['scale','x','y'].map(k=><label key={k}>{k}<input type="number" min={k==='scale'?100:-30} max={k==='scale'?180:30} value={shot[edge][k]} onChange={e=>setEditing({...editing,shots:editing.shots.map((s,j)=>j===i?{...s,[edge]:{...s[edge],[k]:+e.target.value}}:s)})}/></label>)}</fieldset>)}</details>)}<div className="creatorButtons"><button onClick={()=>setEditing(structuredClone(creatorStyles.find(s=>s.name===editing.name)||creatorStyles[0]))}>Reset to default</button><button onClick={store}>Save style</button><button onClick={()=>run(()=>download(C.validateStyle(editing),editing.name+'.rancut-style'))}>Export style</button><button onClick={()=>setEditing(null)}>Cancel edit</button></div></div>}
 {error&&<p className="exportError" role="alert">{error}</p>}</div></div>;
}
