import React,{useEffect,useRef,useState} from 'react';
import * as T from './timeline.js';

const clamp01=n=>T.clamp(n,0,1);
export default function FrameDialog({kind='crop',image,loading=false,loadFrame,duration=0,initialTime=0,initial,onApply,onClose}){
 const ref=useRef(),stage=useRef(),request=useRef(0);
 const [preview,setPreview]=useState(''),[pending,setPending]=useState(false),[frameTime,setFrameTime]=useState(initialTime),[renderTime,setRenderTime]=useState(initialTime),[aspect,setAspect]=useState(16/9);
 useEffect(()=>()=>{request.current++;},[]);
 const chooseFrame=async at=>{at=T.clamp(at,0,Math.max(0,duration-.001));const token=++request.current;setFrameTime(at);setPending(true);setError('');try{const next=await loadFrame(at);if(!next)throw Error('Frame unavailable. Choose another time.');if(request.current===token){setPreview(next);setRenderTime(at);};}catch(e){if(request.current===token)setError(e.message);}finally{if(request.current===token)setPending(false);}};
 image=preview||image;loading=loading||pending;
 const base=kind==='crop'?{left:0,right:0,top:0,bottom:0}:{x:.3,y:.08,width:.4,height:.42,headroom:.04};
 const [value,setValue]=useState({...base,...initial}),[error,setError]=useState('');
 useEffect(()=>{ref.current.showModal();return()=>ref.current?.close();},[]);
 const update=(key,n)=>setValue(v=>({...v,[key]:clamp01(Number(n)||0)}));
 const pointer=e=>{if(e.button!==0)return;const box=stage.current.getBoundingClientRect(),sx=(e.clientX-box.left)/box.width,sy=(e.clientY-box.top)/box.height,start={...value};
  const move=ev=>{const x=clamp01((ev.clientX-box.left)/box.width),y=clamp01((ev.clientY-box.top)/box.height);if(kind==='crop'){setValue({...start,left:Math.min(sx,x),right:1-Math.max(sx,x),top:Math.min(sy,y),bottom:1-Math.max(sy,y)});}else{setValue({...start,x:Math.min(sx,x),y:Math.min(sy,y),width:Math.max(.05,Math.abs(x-sx)),height:Math.max(.05,Math.abs(y-sy))});}};
  const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true});};
 const apply=()=>{try{if(kind==='crop'&&(value.left+value.right>=.95||value.top+value.bottom>=.95))throw Error('Keep some visible picture area.');if(kind==='subject'&&(value.x+value.width>1||value.y+value.height>1))throw Error('Keep the complete subject box inside the frame.');onApply(value);}catch(e){setError(e.message);}};
 const box=kind==='crop'?{left:value.left,top:value.top,width:1-value.left-value.right,height:1-value.top-value.bottom}:{left:value.x,top:value.y,width:value.width,height:value.height};
 return <dialog className="workflowDialog frameDialog" ref={ref} onCancel={onClose}><header><div><h2>{kind==='crop'?'Clean picture edges':'Protect person framing'}</h2><p>{kind==='crop'?'Drag a box around the picture area to keep. This never zooms or changes your body size.':'Draw around the head/face or upper body to keep visible. Belly below the box may be cropped by zoom.'}</p></div><button onClick={onClose}>×</button></header><div className="workflowBody">{loadFrame&&duration>0&&<div className="frameSeek"><label>Choose video frame · {Math.floor(frameTime/60)}:{(frameTime%60).toFixed(2).padStart(5,'0')}<input aria-label="Choose video frame" type="range" min="0" max={Math.max(0,duration-.001)} step=".033333" value={frameTime} onChange={e=>setFrameTime(+e.target.value)} onPointerUp={e=>chooseFrame(+e.currentTarget.value)} onKeyUp={e=>chooseFrame(+e.currentTarget.value)}/></label><div><button disabled={loading} onClick={()=>chooseFrame(Math.max(0,frameTime-1))}>−1 sec</button><input aria-label="Frame time seconds" type="number" min="0" max={Math.max(0,duration-.001)} step=".01" value={frameTime} onChange={e=>setFrameTime(T.clamp(+e.target.value||0,0,Math.max(0,duration-.001)))}/><button disabled={loading} onClick={()=>chooseFrame(frameTime)}>Show frame</button><button disabled={loading} onClick={()=>chooseFrame(Math.min(duration-.001,frameTime+1))}>+1 sec</button></div></div>}<div ref={stage} style={{aspectRatio:aspect}} className="frameStage" onPointerDown={image&&!loading?pointer:undefined}>{image?<img draggable={false} src={image} alt="Current video frame" onLoad={e=>setAspect(e.currentTarget.naturalWidth/e.currentTarget.naturalHeight)}/>:<div className="frameFallback">{loading?'Loading the selected clip at the current playhead…':'Preview frame unavailable.'}</div>}<div className="frameBox" style={{left:(box.left*100)+'%',top:(box.top*100)+'%',width:(box.width*100)+'%',height:(box.height*100)+'%'}}/></div><small>{kind==='subject'?'Keep the head inside the box. Bottom cropping is allowed outside this box. This is manual framing, not moving-person tracking.':'Everything outside the box becomes transparent. Your original scale and position stay unchanged.'}</small><div className="frameNumbers">{(kind==='crop'?['left','right','top','bottom']:['x','y','width','height','headroom']).map(k=><label key={k}>{k}<input disabled={loading} type="number" min="0" max="1" step=".01" value={value[k]} onChange={e=>update(k,e.target.value)}/></label>)}</div>{error&&<p className="exportError">{error}</p>}</div><footer><button onClick={onClose}>Cancel</button><button className="primary" disabled={loading||!image||!!error||Math.abs(frameTime-renderTime)>.0001} onClick={apply}>{kind==='crop'?'Apply clean edges':'Use protected framing'}</button></footer></dialog>;
}
