import React,{useEffect,useRef,useState} from 'react';
import {activateLicense,checkLicenseStatus,clearSavedLicenseKey,getSavedLicenseKey} from './license-client.js';

export default function HelpPanel({onClose,diagnostics}){
 const [feedback,setFeedback]=useState(''),[feedbackType,setFeedbackType]=useState('Feature request'),[updateMessage,setUpdateMessage]=useState(''),[updateAvailable,setUpdateAvailable]=useState(false),[tab,setTab]=useState('Start');
 const dialog=useRef();
 const [licenseKey,setLicenseKey]=useState(getSavedLicenseKey),[licenseInfo,setLicenseInfo]=useState(null),[licenseBusy,setLicenseBusy]=useState(false),[licenseMessage,setLicenseMessage]=useState('');
 useEffect(()=>{dialog.current.showModal();return()=>dialog.current?.close();},[]);
 useEffect(()=>{checkLicenseStatus().then(setLicenseInfo).catch(error=>setLicenseMessage(error.message));},[]);
 const saveFeedback=()=>{const text=`RanCut ${feedbackType}\nVersion: 0.5.8 Preview · Build 58\n\n${feedback.trim()}\n`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='RanCut-feedback.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const checkUpdates=async()=>{setUpdateMessage('Checking…');try{if(!window.rancut?.checkUpdates){setUpdateMessage('Update checks are available in the desktop app.');return;}const r=await window.rancut.checkUpdates();setUpdateAvailable(!!r.available);setUpdateMessage(!r.configured?'Release server is not configured yet.':r.available?'Version '+r.latest+' is available.':'You have the latest published version.');}catch(e){setUpdateMessage(e.message);}};
 const refreshLicense=async()=>{setLicenseBusy(true);setLicenseMessage('Checking license…');try{const result=await checkLicenseStatus();setLicenseInfo(result);setLicenseMessage(result.active?'License is active.':'No active license.');}catch(error){setLicenseMessage(error.message);}finally{setLicenseBusy(false);}};
 const submitLicense=async()=>{setLicenseBusy(true);setLicenseMessage('Activating…');try{const result=await activateLicense(licenseKey);setLicenseInfo(result);setLicenseMessage(`Activated ${result.plan||'license'} plan.`);}catch(error){setLicenseMessage(error.message);}finally{setLicenseBusy(false);}};
 const removeLicense=()=>{clearSavedLicenseKey();setLicenseInfo({ok:true,active:false});setLicenseKey('');setLicenseMessage('Local license removed from this installation.');};
 const download=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({...diagnostics,platform:navigator.platform},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='RanCut-diagnostics.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const account=<><h3>Account &amp; Plan</h3><p>Free trial includes 2 successful Auto Edits per calendar month. A private-beta license unlocks Auto Edit without consuming trial uses.</p><div className="licenseBox"><label>License key<input aria-label="License key" value={licenseKey} onChange={e=>setLicenseKey(e.target.value)} placeholder="RC-MONTHLY-…" autoCapitalize="characters" spellCheck="false"/></label><div className="licenseActions"><button disabled={licenseBusy||!licenseKey.trim()} onClick={submitLicense}>Activate</button><button disabled={licenseBusy} onClick={refreshLicense}>Check status</button><button disabled={licenseBusy||!licenseKey} onClick={removeLicense}>Remove local key</button></div><p role="status">{licenseMessage||(licenseInfo?.active?`Active ${licenseInfo.plan||'license'} · expires ${new Date(licenseInfo.expiresAt).toLocaleDateString()}`:'No active license')}</p></div><p>License activation is tied to this installation. Do not share your key publicly.</p></>;
 return <dialog className="helpDialog" ref={dialog} onCancel={onClose}><header><div><small>LOCAL CREATOR EDITOR</small><h2>RanCut <small>0.5.8 · Preview</small></h2></div><button aria-label="Close help" onClick={onClose}>×</button></header><nav>{['Start','Shortcuts','About','Feedback','Account','Privacy','Licences','Updates'].map(t=><button className={t===tab?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</nav><section>{tab==='Start'?<><h3>Your first edit</h3><ol><li>Import footage. Put the background on V1 and the person on V2.</li><li>Select the person → Chroma → enable key and sample the green screen.</li><li>Audio → Detect pauses → review before removing.</li><li>Styles → choose the person track → Simple or Dynamic → Apply.</li><li>Click + on a cut for Transitions.</li></ol><p>Auto Edit saves an editable project copy. Exports always use originals.</p></>:tab==='Shortcuts'?<><h3>Keyboard shortcuts</h3><p>Space: play/pause · X: split · Z: crop left · C: trim right · Q/W: ripple · G: close gap · L: link · Ctrl+A: select all · Ctrl+S: save · Ctrl+Z: undo.</p></>:tab==='About'?<><img className="aboutIcon" src="./brand-icon.png" alt="RanCut icon"/><h3>RanCut — built for creators</h3><p>Version 0.5.8 Preview · Build 58</p><p>Local video editing, Creator Styles, chroma key and GPU-capable export.</p></>:tab==='Feedback'?<><h3>Request a feature / Report a bug</h3><label>Type<select value={feedbackType} onChange={e=>setFeedbackType(e.target.value)}><option>Feature request</option><option>Bug report</option></select></label><textarea aria-label="Feedback details" placeholder="What were you trying to do?" value={feedback} onChange={e=>setFeedback(e.target.value)}/><div className="feedbackActions"><button disabled={!feedback.trim()} onClick={saveFeedback}>Save feedback draft</button></div></>:tab==='Account'?account:tab==='Privacy'?<><h3>Local by design</h3><p>Media, analysis, previews and exports stay on this computer. Diagnostics are downloaded only when you click the button.</p></>:tab==='Licences'?<><h3>Third-party software</h3><p>React, Vite, Lucide, Electron and FFmpeg include third-party licences. Review the notices in the source before public distribution.</p></>:<><h3>Updates</h3><p>Installed version: 0.5.8 (preview).</p><button onClick={checkUpdates}>Check for updates</button>{updateAvailable&&<button onClick={()=>window.rancut.openRelease().catch(e=>setUpdateMessage(e.message))}>Open release page</button>}<p role="status">{updateMessage}</p></>}</section><footer><button onClick={download}>Download diagnostics</button><button onClick={onClose}>Done</button></footer></dialog>;
}
