import FeedbackPanel from './FeedbackPanel.jsx';
import UpdatePanel from './UpdatePanel.jsx';
import React,{useEffect,useRef,useState} from 'react';
import {activateLicense,checkLicenseStatus,checkAccountStatus,clearSavedLicenseKey,getSavedLicenseKey} from './license-client.js';

const sections=['Start','Shortcuts','About','Feedback','Plans','Account','Privacy','Licences','Updates'];

export default function HelpPanel({onClose,diagnostics,initialTab="Start"}){
 const [tab,setTab]=useState(initialTab);
 const dialog=useRef();
 const [licenseKey,setLicenseKey]=useState(getSavedLicenseKey),[licenseInfo,setLicenseInfo]=useState(null),[accountInfo,setAccountInfo]=useState(null),[licenseBusy,setLicenseBusy]=useState(false),[licenseMessage,setLicenseMessage]=useState('');
 useEffect(()=>{dialog.current?.showModal();return()=>dialog.current?.close();},[]);
 useEffect(()=>{Promise.all([checkLicenseStatus().catch(()=>null),checkAccountStatus().catch(()=>null)]).then(([license,account])=>{setLicenseInfo(license);setAccountInfo(account);});},[]);
 const refreshLicense=async()=>{setLicenseBusy(true);setLicenseMessage('Checking plan…');try{const [result,account]=await Promise.all([checkLicenseStatus(),checkAccountStatus()]);setLicenseInfo(result);setAccountInfo(account);setLicenseMessage(result.active?'License is active.':account.trialActive?'Private beta trial is active.':'Free plan is active.');}catch(error){setLicenseMessage(error.message);}finally{setLicenseBusy(false);}};
 const submitLicense=async()=>{setLicenseBusy(true);setLicenseMessage('Activating…');try{const result=await activateLicense(licenseKey);setLicenseInfo(result);setAccountInfo(await checkAccountStatus());setLicenseMessage(`Activated ${result.plan||'license'} plan.`);}catch(error){setLicenseMessage(error.message);}finally{setLicenseBusy(false);}};
 const removeLicense=()=>{clearSavedLicenseKey();setLicenseInfo({ok:true,active:false});setLicenseKey('');setLicenseMessage('Local license removed from this installation.');};
 const download=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({...diagnostics,platform:navigator.platform},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='RanCut-diagnostics.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const planLabel=accountInfo?.trialActive?'30-day Pro trial':accountInfo?.licensed?`Pro · ${accountInfo.plan||'licensed'}`:'Free plan';
 const account=<><div className="helpEyebrow">ACCOUNT &amp; PLAN</div><h3>{planLabel}</h3><p>{accountInfo?.trialActive?'Your first 30 days include every current Pro feature, including unlimited Auto Edit and 2K/4K export.': 'Free includes unlimited manual editing, 1080p export and 2 successful Auto Edits per calendar month. Pro unlocks unlimited Auto Edit plus 2K/4K export.'}</p><div className="licenseBox"><label>License key<input aria-label="License key" value={licenseKey} onChange={e=>setLicenseKey(e.target.value)} placeholder="RC-MONTHLY-…" autoCapitalize="characters" spellCheck="false"/></label><div className="licenseActions"><button disabled={licenseBusy||!licenseKey.trim()} onClick={submitLicense}>Activate</button><button disabled={licenseBusy} onClick={refreshLicense}>Check status</button><button disabled={licenseBusy||!licenseKey} onClick={removeLicense}>Remove local key</button></div><p role="status">{licenseMessage||(accountInfo?.trialActive?`Trial active · ends ${new Date(accountInfo.trialEndsAt).toLocaleDateString()}`:licenseInfo?.active?`Active ${licenseInfo.plan||'license'} · expires ${new Date(licenseInfo.expiresAt).toLocaleDateString()}`:'No active license')}</p></div><p className="helpMuted">License activation is tied to this installation. Do not share your key publicly.</p></>;
 const content={
  Start:<><div className="helpEyebrow">QUICK START</div><h3>Your first edit</h3><p className="helpLead">A short route from footage to a clean, editable cut.</p><ol className="helpSteps"><li><b>Import footage</b><span>Put the background on V1 and the person on V2.</span></li><li><b>Key the subject</b><span>Select the person → Chroma → enable key and sample the green screen.</span></li><li><b>Clean the edit</b><span>Audio → Detect pauses → review before removing.</span></li><li><b>Set a style</b><span>Styles → choose the person track → Simple or Dynamic → Apply.</span></li><li><b>Add transitions</b><span>Click + on a cut to choose a transition.</span></li></ol><div className="helpCallout"><b>Auto Edit stays editable</b><span>It saves a project copy. Exports always use original media, never a temporary preview proxy.</span></div><button className="planCompareLink" onClick={()=>setTab('Plans')}>Compare Free and Pro plans</button></>,
  Shortcuts:<><div className="helpEyebrow">WORK FASTER</div><h3>Keyboard shortcuts</h3><p className="helpLead">Keep the timeline focused and make common edits without hunting through menus.</p><div className="shortcutGrid"><span><kbd>Space</kbd> Play / pause</span><span><kbd>X</kbd> Split</span><span><kbd>Z</kbd> Crop left</span><span><kbd>C</kbd> Trim right</span><span><kbd>Q</kbd><kbd>W</kbd> Ripple trim</span><span><kbd>G</kbd> Close gap</span><span><kbd>L</kbd> Link clips</span><span><kbd>Ctrl / ⌘ A</kbd> Select all</span><span><kbd>Ctrl / ⌘ S</kbd> Save</span><span><kbd>Ctrl / ⌘ Z</kbd> Undo</span></div></>,
  About:<><div className="helpEyebrow">ABOUT RANCUT</div><div className="aboutHero"><img className="aboutIcon" src="./brand-icon.png" alt="RanCut icon"/><div><h3>Local tools for creator-led edits</h3><p>Fast previews, editable Creator Styles, chroma key and GPU-capable export without uploading your media.</p></div></div><div className="aboutMeta"><span><b>Version</b>0.6.4 Preview</span><span><b>Release</b>Build 64</span><span><b>Media</b>Local by design</span></div></>,
  Feedback:<FeedbackPanel/>,
  Plans:<><div className="helpEyebrow">PRIVATE BETA PLANS</div><h3>Free and Pro plan details</h3><p className="helpLead">Every new installation starts with a 30-day trial of all current Pro features. After the trial, continue on Free or activate a Pro subscription key.</p><div className="planComparison" aria-label="Free and Pro plan comparison"><article className="planCard trialPlan"><small>FIRST 30 DAYS</small><h4>Pro trial</h4><ul><li>All current editing features</li><li>Unlimited Auto Edit</li><li>1080p, 2K and 4K export</li></ul></article><article className="planCard"><small>AFTER TRIAL</small><h4>Free</h4><ul><li>Unlimited manual editing</li><li>Up to 1080p export</li><li>2 successful Auto Edits per calendar month</li><li>2K and 4K export unavailable</li></ul></article><article className="planCard proPlan"><small>SUBSCRIPTION KEY</small><h4>Pro</h4><ul><li>Unlimited Auto Edit</li><li>1080p, 2K and 4K export</li><li>Monthly or yearly access key</li></ul></article></div><p className="helpPlanNote">Online purchase is not available yet during the private beta. RanCut will provide Pro keys directly.</p><button className="planCompareLink" onClick={()=>setTab('Account')}>Enter or check a Pro license key</button></>,
  Account:account,
  Privacy:<><div className="helpEyebrow">TRUST &amp; CONTROL</div><h3>Local by design</h3><p className="helpLead">Your source media, analysis, previews and exports stay on this computer.</p><div className="helpInfoList"><span><b>Source files</b><small>Never copied into a cloud project by RanCut.</small></span><span><b>Diagnostics</b><small>Downloaded only when you explicitly click the button below.</small></span><span><b>Release checks</b><small>The app checks release metadata at startup and periodically, sending its version.</small></span><span><b>Feedback</b><small>Submitted messages and app version go to the private admin inbox. Failed requests stay on this device for retry.</small></span></div></>,
  Licences:<><div className="helpEyebrow">CREDITS</div><h3>Third-party software</h3><p className="helpLead">RanCut is assembled from well-known open-source building blocks.</p><div className="helpInfoList"><span><b>React · Vite · Lucide</b><small>Application UI and local development toolchain.</small></span><span><b>Electron</b><small>Desktop shell, filesystem bridge and secure local IPC.</small></span><span><b>FFmpeg</b><small>Media analysis, encoding and compatibility export.</small></span></div><p className="helpMuted">Review the notices in the source distribution before public redistribution.</p></>,
  Updates:<UpdatePanel/>
 };
 return <dialog className="helpDialog" ref={dialog} onCancel={onClose}><header className="helpHeader"><div className="helpIdentity"><img src="./brand-icon.png" alt="RanCut icon"/><div><small>LOCAL CREATOR EDITOR</small><h2>Help &amp; About <em>0.6.4</em> <small className="privateBeta">PRIVATE BETA</small></h2><p>Learn the workflow, check your license and keep the beta current.</p></div></div><button className="helpClose" aria-label="Close help" onClick={onClose}>×</button></header><div className="helpBody"><nav className="helpRail" aria-label="Help sections"><div className="helpRailTitle">RANCUT GUIDE</div>{sections.map(t=><button className={t===tab?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</nav><section className="helpContent">{content[tab]}</section></div><footer className="helpFooter"><button onClick={download}>Download diagnostics</button><button className="primary" onClick={onClose}>Done</button></footer></dialog>;
}
