import React,{useEffect,useRef,useState} from 'react';
import {activateLicense,checkLicenseStatus,clearSavedLicenseKey,getSavedLicenseKey,submitFeedback} from './license-client.js';

const sections=['Start','Shortcuts','About','Feedback','Account','Privacy','Licences','Updates'];

export default function HelpPanel({onClose,diagnostics}){
 const [feedback,setFeedback]=useState(''),[feedbackType,setFeedbackType]=useState('Feature request'),[feedbackBusy,setFeedbackBusy]=useState(false),[feedbackMessage,setFeedbackMessage]=useState(''),[updateMessage,setUpdateMessage]=useState(''),[updateAvailable,setUpdateAvailable]=useState(false),[updateInfo,setUpdateInfo]=useState(null),[tab,setTab]=useState('Start');
 const dialog=useRef();
 const [licenseKey,setLicenseKey]=useState(getSavedLicenseKey),[licenseInfo,setLicenseInfo]=useState(null),[licenseBusy,setLicenseBusy]=useState(false),[licenseMessage,setLicenseMessage]=useState('');
 useEffect(()=>{dialog.current?.showModal();return()=>dialog.current?.close();},[]);
 useEffect(()=>{checkLicenseStatus().then(setLicenseInfo).catch(error=>setLicenseMessage(error.message));},[]);
 const sendFeedback=async()=>{setFeedbackBusy(true);setFeedbackMessage('Sending to RanCut Platform…');try{const entry=await submitFeedback({type:feedbackType,message:feedback,diagnostics});setFeedback('');setFeedbackMessage(`Submitted to RanCut Platform · request ${entry.id.slice(0,8)}.`);}catch(error){setFeedbackMessage(error.message||'Could not submit feedback.');}finally{setFeedbackBusy(false);}};
 const checkUpdates=async()=>{setUpdateMessage('Checking the release channel…');try{if(!window.rancut?.checkUpdates){setUpdateMessage('Update checks are available in the desktop app.');return;}const r=await window.rancut.checkUpdates();setUpdateInfo(r);setUpdateAvailable(!!r.available);setUpdateMessage(!r.configured?'Release server is not configured yet.':r.available?`Version ${r.latest} is available${r.notes?` · ${r.notes}`:''}.`:'You have the latest published version.');}catch(e){setUpdateMessage(e.message);}};
 const downloadUpdate=()=>{const open=window.rancut?.openUpdate||window.rancut?.openRelease;if(!open){setUpdateMessage('Update downloads are available in the desktop app.');return;}open(updateInfo?.downloadUrl).catch(e=>setUpdateMessage(e.message));};
 const refreshLicense=async()=>{setLicenseBusy(true);setLicenseMessage('Checking license…');try{const result=await checkLicenseStatus();setLicenseInfo(result);setLicenseMessage(result.active?'License is active.':'No active license.');}catch(error){setLicenseMessage(error.message);}finally{setLicenseBusy(false);}};
 const submitLicense=async()=>{setLicenseBusy(true);setLicenseMessage('Activating…');try{const result=await activateLicense(licenseKey);setLicenseInfo(result);setLicenseMessage(`Activated ${result.plan||'license'} plan.`);}catch(error){setLicenseMessage(error.message);}finally{setLicenseBusy(false);}};
 const removeLicense=()=>{clearSavedLicenseKey();setLicenseInfo({ok:true,active:false});setLicenseKey('');setLicenseMessage('Local license removed from this installation.');};
 const download=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({...diagnostics,platform:navigator.platform},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='RanCut-diagnostics.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const account=<><div className="helpEyebrow">ACCOUNT &amp; PLAN</div><h3>Keep your editing limits clear</h3><p>Free trial includes 2 successful Auto Edits per calendar month. A private-beta license unlocks Auto Edit without consuming trial uses.</p><div className="licenseBox"><label>License key<input aria-label="License key" value={licenseKey} onChange={e=>setLicenseKey(e.target.value)} placeholder="RC-MONTHLY-…" autoCapitalize="characters" spellCheck="false"/></label><div className="licenseActions"><button disabled={licenseBusy||!licenseKey.trim()} onClick={submitLicense}>Activate</button><button disabled={licenseBusy} onClick={refreshLicense}>Check status</button><button disabled={licenseBusy||!licenseKey} onClick={removeLicense}>Remove local key</button></div><p role="status">{licenseMessage||(licenseInfo?.active?`Active ${licenseInfo.plan||'license'} · expires ${new Date(licenseInfo.expiresAt).toLocaleDateString()}`:'No active license')}</p></div><p className="helpMuted">License activation is tied to this installation. Do not share your key publicly.</p></>;
 const content={
  Start:<><div className="helpEyebrow">QUICK START</div><h3>Your first edit</h3><p className="helpLead">A short route from footage to a clean, editable cut.</p><ol className="helpSteps"><li><b>Import footage</b><span>Put the background on V1 and the person on V2.</span></li><li><b>Key the subject</b><span>Select the person → Chroma → enable key and sample the green screen.</span></li><li><b>Clean the edit</b><span>Audio → Detect pauses → review before removing.</span></li><li><b>Set a style</b><span>Styles → choose the person track → Simple or Dynamic → Apply.</span></li><li><b>Add transitions</b><span>Click + on a cut to choose a transition.</span></li></ol><div className="helpCallout"><b>Auto Edit stays editable</b><span>It saves a project copy. Exports always use original media, never a temporary preview proxy.</span></div></>,
  Shortcuts:<><div className="helpEyebrow">WORK FASTER</div><h3>Keyboard shortcuts</h3><p className="helpLead">Keep the timeline focused and make common edits without hunting through menus.</p><div className="shortcutGrid"><span><kbd>Space</kbd> Play / pause</span><span><kbd>X</kbd> Split</span><span><kbd>Z</kbd> Crop left</span><span><kbd>C</kbd> Trim right</span><span><kbd>Q</kbd><kbd>W</kbd> Ripple trim</span><span><kbd>G</kbd> Close gap</span><span><kbd>L</kbd> Link clips</span><span><kbd>Ctrl / ⌘ A</kbd> Select all</span><span><kbd>Ctrl / ⌘ S</kbd> Save</span><span><kbd>Ctrl / ⌘ Z</kbd> Undo</span></div></>,
  About:<><div className="helpEyebrow">ABOUT RANCUT</div><div className="aboutHero"><img className="aboutIcon" src="./brand-icon.png" alt="RanCut icon"/><div><h3>Local tools for creator-led edits</h3><p>Fast previews, editable Creator Styles, chroma key and GPU-capable export without uploading your media.</p></div></div><div className="aboutMeta"><span><b>Version</b>0.5.9 Preview</span><span><b>Release</b>Build 59</span><span><b>Media</b>Local by design</span></div></>,
  Feedback:<><div className="helpEyebrow">RANCUT PLATFORM</div><h3>Request a feature or report a bug</h3><p className="helpLead">Submit it directly to the private RanCut Platform. Only your Platform Admin dashboard shows submitted requests.</p><label>Type<select value={feedbackType} disabled={feedbackBusy} onChange={e=>setFeedbackType(e.target.value)}><option>Feature request</option><option>Bug report</option></select></label><textarea aria-label="Feedback details" placeholder="What were you trying to do?" value={feedback} disabled={feedbackBusy} onChange={e=>setFeedback(e.target.value)}/><div className="feedbackActions"><button className="primary" disabled={feedbackBusy||feedback.trim().length<5} onClick={sendFeedback}>{feedbackBusy?'Submitting…':'Submit to RanCut Platform'}</button></div><p className="helpStatus" role="status">{feedbackMessage||'Nothing is saved as a local feedback file.'}</p></>,
  Account:account,
  Privacy:<><div className="helpEyebrow">TRUST &amp; CONTROL</div><h3>Local by design</h3><p className="helpLead">Your source media, analysis, previews and exports stay on this computer.</p><div className="helpInfoList"><span><b>Source files</b><small>Never copied into a cloud project by RanCut.</small></span><span><b>Diagnostics</b><small>Downloaded only when you explicitly click the button below.</small></span><span><b>Release checks</b><small>Only the version manifest is requested when you check for updates.</small></span></div></>,
  Licences:<><div className="helpEyebrow">CREDITS</div><h3>Third-party software</h3><p className="helpLead">RanCut is assembled from well-known open-source building blocks.</p><div className="helpInfoList"><span><b>React · Vite · Lucide</b><small>Application UI and local development toolchain.</small></span><span><b>Electron</b><small>Desktop shell, filesystem bridge and secure local IPC.</small></span><span><b>FFmpeg</b><small>Media analysis, encoding and compatibility export.</small></span></div><p className="helpMuted">Review the notices in the source distribution before public redistribution.</p></>,
  Updates:<><div className="helpEyebrow">RELEASE CHANNEL</div><h3>Stay current</h3><p className="helpLead">The desktop app checks an HTTPS manifest. It does not silently replace your install.</p><div className="updateCard"><div><b>Installed</b><span>RanCut 0.5.9 · Preview</span></div><button onClick={checkUpdates}>Check for updates</button></div>{updateAvailable&&<div className="updateReady"><div><b>Update ready</b><span>Version {updateInfo?.latest} is available.</span></div><button className="primary" onClick={downloadUpdate}>Download update</button></div>}<p className="helpStatus" role="status">{updateMessage||'No check run yet.'}</p></>
 };
 return <dialog className="helpDialog" ref={dialog} onCancel={onClose}><header className="helpHeader"><div className="helpIdentity"><img src="./brand-icon.png" alt="RanCut icon"/><div><small>LOCAL CREATOR EDITOR</small><h2>Help &amp; About <em>0.5.9</em></h2><p>Learn the workflow, check your license and keep the beta current.</p></div></div><button className="helpClose" aria-label="Close help" onClick={onClose}>×</button></header><div className="helpBody"><nav className="helpRail" aria-label="Help sections"><div className="helpRailTitle">RANCUT GUIDE</div>{sections.map(t=><button className={t===tab?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</nav><section className="helpContent">{content[tab]}</section></div><footer className="helpFooter"><button onClick={download}>Download diagnostics</button><button className="primary" onClick={onClose}>Done</button></footer></dialog>;
}
