import CreatorPanel,{StyleClipControls} from './CreatorPanel.jsx';
import * as C from './creator.js';
import {soundRuntime,disposeSounds} from './sounds.js';
import React,{useState,useRef,useEffect,useMemo} from 'react';
import {createRoot} from 'react-dom/client';
import {Upload,Play,Pause,Scissors,Download,Eye,EyeOff,Volume2,VolumeX,Lock,Unlock,Film,Music,Image as ImageIcon,Undo2,Redo2,Maximize2,Link2,Trash2,Save,FolderOpen,Plus} from 'lucide-react';
import * as T from './timeline.js';
import * as E from './editing.js';
import {followScroll,fitZoom,MIN_ZOOM,boxSelection} from './timeline-view.js';
import {Renderer} from './renderer.js';
import Waveform from './Waveform.jsx';
import {saveRecovery,loadRecovery,downloadJSON} from './storage.js';
import './style.css';
const fmt=t=>`${String(Math.floor(Math.max(0,t)/60)).padStart(2,'0')}:${Math.max(0,t%60).toFixed(2).padStart(5,'0')}`;
const api=async(url,data,signal)=>{const binary=data instanceof Blob||ArrayBuffer.isView(data)||data instanceof ArrayBuffer;const r=await fetch('/api/'+url,{method:data===undefined?'GET':'POST',headers:{'X-RanCut':'1','Content-Type':binary?'application/octet-stream':'application/json'},body:data===undefined?undefined:binary?data:JSON.stringify(data),signal:signal||AbortSignal.timeout(120000)});const j=await r.json();if(!r.ok)throw Error(j.error||'Local processing failed.');return j;};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function mediaInfo(file,url){if(file.type.startsWith('image/'))return Promise.resolve({type:'image',duration:10});return new Promise((resolve,reject)=>{const type=file.type.startsWith('audio/')?'audio':'video',el=document.createElement(type==='audio'?'audio':'video');const timer=setTimeout(()=>reject(Error('Could not read media metadata.')),20000);el.preload='metadata';el.onloadedmetadata=()=>{clearTimeout(timer);if(!Number.isFinite(el.duration)||el.duration<=0)return reject(Error('Unsupported media duration.'));const info={type,duration:el.duration};el.removeAttribute('src');el.load();resolve(info);};el.onerror=()=>{clearTimeout(timer);reject(Error('Browser cannot decode this file. Convert to H.264/AAC MP4 first.'));};el.src=url;});}
function Slider({name,value,min=0,max=100,step=1,onChange,suffix=''}){return <label className="slider"><span>{name}<b>{Number(value).toFixed(step<1?2:0)}{suffix}</b></span><input aria-label={name} type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(+e.target.value)}/></label>;}
function App(){
 const [outputFolder,setOutputFolder]=useState(''),[exportStage,setExportStage]=useState(''),[exportError,setExportError]=useState(''),[elapsed,setElapsed]=useState(0);
 const exportAbort=useRef(null),exportJob=useRef(null),exportBegan=useRef(0);
 useEffect(()=>{api('output').then(x=>setOutputFolder(x.directory)).catch(()=>{});},[]);
 const [boxMode,setBoxMode]=useState(false),[fullScreen,setFullScreen]=useState(false);
 useEffect(()=>{const update=()=>setFullScreen(!!document.fullscreenElement);document.addEventListener('fullscreenchange',update);return()=>document.removeEventListener('fullscreenchange',update);},[]);
 const [followSuspended,setFollowSuspended]=useState(false),[selectedGap,setSelectedGap]=useState(null);
 const followTimer=useRef(null);
 const suspendFollow=()=>{setFollowSuspended(true);clearTimeout(followTimer.current);followTimer.current=setTimeout(()=>setFollowSuspended(false),2500);};
 useEffect(()=>()=>clearTimeout(followTimer.current),[]);
 const [scope,setScope]=useState('all'),[snapping,setSnapping]=useState(true),[previewScale,setPreviewScale]=useState(.5),[timelineHeight,setTimelineHeight]=useState(310),[showMedia,setShowMedia]=useState(true),[showInspector,setShowInspector]=useState(true),[box,setBox]=useState(null),[ghost,setGhost]=useState(null),[gapMenu,setGapMenu]=useState(null),[copiedFx,setCopiedFx]=useState(null),[effectSection,setEffectSection]=useState('all');
 const previewRef=useRef(.5),dragRef=useRef(null),suppressClick=useRef(false);
 previewRef.current=previewScale;

 const [project,setProject]=useState(T.emptyProject),[media,setMedia]=useState([]),[selected,setSelected]=useState(null),[selectedIds,setSelectedIds]=useState(new Set()),[time,setTime]=useState(0),[playing,setPlaying]=useState(false),[zoom,setZoom]=useState(80),[status,setStatus]=useState('Ready'),[tab,setTab]=useState('video'),[leftTab,setLeftTab]=useState('media'),[follow,setFollow]=useState(true),[ripple,setRipple]=useState(true),[scroll,setScroll]=useState(0),[viewport,setViewport]=useState(1000),[threshold,setThreshold]=useState(-38),[pauseLength,setPauseLength]=useState(.55),[padding,setPadding]=useState(.12),[pauses,setPauses]=useState(null),[exportOpen,setExportOpen]=useState(false),[exporting,setExporting]=useState(false),[progress,setProgress]=useState(0),[exportWidth,setExportWidth]=useState(1920),[quality,setQuality]=useState('High'),[result,setResult]=useState(null),[ready,setReady]=useState(false),[meter,setMeter]=useState(-60),[picking,setPicking]=useState(false),[ffmpeg,setFfmpeg]=useState(false),[encoderInfo,setEncoderInfo]=useState({selected:'libx264',mode:'cpu',hardware:[]}),[importing,setImporting]=useState(false);
 const pRef=useRef(project),mRef=useRef(media),timeRef=useRef(time),playingRef=useRef(false),anchor=useRef({time:0,perf:0}),exportRef=useRef(false),cancelRef=useRef(false),history=useRef([]),future=useRef([]),canvas=useRef(),viewer=useRef(),renderer=useRef(),scroller=useRef(),labels=useRef(),fileInput=useRef(),projectInput=useRef(),fxGroup=useRef({}),lastError=useRef(''),mounted=useRef(true),analysisQueue=useRef(Promise.resolve()),relinkFolderInput=useRef(),singleRelinkInput=useRef(),relinkTarget=useRef(null);
 const updateMedia=fn=>{mRef.current=fn(mRef.current);setMedia(mRef.current);};
 const put=p=>{pRef.current=p;setProject(p);};
 const pause=()=>{playingRef.current=false;setPlaying(false);renderer.current?.pause();};
 const seek=t=>{const n=T.clamp(t,0,Math.max(0,T.duration(pRef.current)));timeRef.current=n;setTime(n);anchor.current={time:n,perf:performance.now()};};
 const fail=e=>{setStatus(e.message||String(e));};
 const toggleFullscreen=()=>{(document.fullscreenElement?document.exitFullscreen():viewer.current.requestFullscreen()).catch(fail);};
 const commit=(fn,label='Updated',record=true)=>{if(exportRef.current)return false;try{const before=pRef.current,next=typeof fn==='function'?fn(before):fn;T.finish(before,next);if(record){history.current.push(structuredClone(before));if(history.current.length>80)history.current.shift();future.current=[];}put(next);setPauses(null);setStatus(label);if(timeRef.current>T.duration(next))seek(T.duration(next));return true;}catch(e){fail(e);return false;}};
 const undo=()=>{if(exportRef.current||!history.current.length)return;pause();future.current.push(pRef.current);put(history.current.pop());setPauses(null);seek(Math.min(timeRef.current,T.duration(pRef.current)));setStatus('Undo');};
 const redo=()=>{if(exportRef.current||!future.current.length)return;pause();history.current.push(pRef.current);put(future.current.pop());setPauses(null);setStatus('Redo');};
 const choose=(id,multi=false)=>{setSelectedGap(null);let n=new Set(selectedIds);if(multi){n.has(id)?n.delete(id):n.add(id);}else if(!n.has(id))n=new Set([id]);setSelectedIds(n);setSelected(n.has(id)?id:[...n].at(-1)||null);setPauses(null);setPicking(false);const c=pRef.current.clips.find(c=>c.id===id);setTab(pRef.current.tracks.find(t=>t.id===c?.trackId)?.type==='audio'?'audio':'video');};
 const selection=()=>[...selectedIds].filter(id=>pRef.current.clips.some(c=>c.id===id));
 const selectToEnd=()=>{try{const ids=E.selectFrom(pRef.current,selected,scope==='all');setSelectedGap(null);setSelectedIds(new Set(ids));setStatus(`${ids.length} clips selected from here to end · ${scope}`);}catch(e){fail(e);}};
 const selectAll=()=>{setSelectedGap(null);const ids=pRef.current.clips.filter(c=>!pRef.current.tracks.find(t=>t.id===c.trackId).locked).map(c=>c.id);setSelectedIds(new Set(ids));setSelected(ids[0]||null);};
 const clearSelection=()=>{setSelectedGap(null);setSelectedIds(new Set());setSelected(null);};
 const pasteFx=()=>{if(copiedFx)commit(p=>E.pasteEffects(p,selection(),copiedFx,effectSection),'Effects pasted');};
 const clip=project.clips.find(c=>c.id===selected),meta=project.media.find(m=>m.id===clip?.mediaId),runtime=meta?.sound?soundRuntime(meta):media.find(m=>m.id===clip?.mediaId),duration=T.duration(project),displayDuration=Math.max(12,duration),timelineWidth=Math.max(viewport,(displayDuration+2)*zoom),missing=project.media.filter(m=>!m.sound&&!media.find(x=>x.id===m.id)?.url);
 const changeFx=(id,section,key,value)=>{const group=`${id}:${section}:${key}`,now=performance.now(),record=fxGroup.current.key!==group||now-fxGroup.current.time>700;fxGroup.current={key:group,time:now};commit(p=>({...p,clips:p.clips.map(c=>{if(c.id!==id)return c;const fx={...T.fxDefault(),...c.fx};return {...c,fx:section?{...fx,[section]:{...fx[section],[key]:value}}:{...fx,[key]:value}};})}),'Effect updated',record);};
 const audioId=()=>{if(!clip)return null;return project.tracks.find(t=>t.id===clip.trackId)?.type==='audio'?clip.id:clip.linkedId;};
 const toggle=async()=>{if(exportRef.current)return;if(playingRef.current){pause();return;}if(!duration)return;if(missing.length){setStatus('Relink missing media before playback.');return;}try{await renderer.current.resumeAudio();if(timeRef.current>=duration)seek(0);setFollowSuspended(false);clearTimeout(followTimer.current);anchor.current={time:timeRef.current,perf:performance.now()};playingRef.current=true;setPlaying(true);}catch(e){fail(e);}};
 useEffect(()=>{mounted.current=true;renderer.current=new Renderer(canvas.current);api('health').then(x=>{setFfmpeg(x.ffmpeg);setEncoderInfo({selected:x.encoder||'libx264',mode:x.encoderMode||'cpu',hardware:x.hardwareEncoders||[]});}).catch(fail);loadRecovery().then(p=>{if(p&&p.clips.length){T.validate(p);put(p);setStatus('Recovered project — use Relink media to reconnect source files.');}}).catch(fail).finally(()=>setReady(true));let frame,report=0,lastUI=0;
  const loop=async()=>{if(!mounted.current)return;try{if(!exportRef.current){const p=pRef.current;if(playingRef.current){const t=anchor.current.time+(performance.now()-anchor.current.perf)/1000;if(t>=T.duration(p)){pause();timeRef.current=T.duration(p);setTime(timeRef.current);}else{timeRef.current=t;if(performance.now()-lastUI>40){setTime(t);lastUI=performance.now();}}}await renderer.current.draw(p,mRef.current,timeRef.current,{play:playingRef.current,width:p.width*previewRef.current});if(performance.now()-report>120){setMeter(renderer.current.meter());report=performance.now();}}}catch(e){if(e.message!==lastError.current){lastError.current=e.message;fail(e);}pause();}frame=requestAnimationFrame(loop);};frame=requestAnimationFrame(loop);
  return()=>{mounted.current=false;cancelAnimationFrame(frame);renderer.current.dispose();disposeSounds();for(const m of mRef.current)if(m.url)URL.revokeObjectURL(m.url);};
 },[]);
 useEffect(()=>{if(!ready)return;const handle=setTimeout(()=>saveRecovery(project).catch(()=>setStatus('Autosave unavailable — use Save project.')),500);return()=>clearTimeout(handle);},[project,ready]);
 useEffect(()=>{const warn=e=>{if(!window.rancut?.desktop&&pRef.current.clips.length){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[]);
 useEffect(()=>{const el=scroller.current;if(!el)return;const ob=new ResizeObserver(()=>setViewport(el.clientWidth));ob.observe(el);return()=>ob.disconnect();},[]);
 useEffect(()=>{const el=scroller.current;if(!el)return;const next=followScroll({time,zoom,left:el.scrollLeft,width:el.clientWidth,total:el.scrollWidth,enabled:follow,suspended:followSuspended});if(next!==el.scrollLeft)el.scrollLeft=next;},[time,zoom,follow,followSuspended,viewport,displayDuration]);
 useEffect(()=>{const el=scroller.current;if(!el)return;const wheel=e=>{if(e.ctrlKey){e.preventDefault();const r=el.getBoundingClientRect(),x=e.clientX-r.left,t=(el.scrollLeft+x)/zoom,nz=T.clamp(zoom*(e.deltaY<0?1.2:1/1.2),MIN_ZOOM,2400);suspendFollow();setZoom(nz);requestAnimationFrame(()=>el.scrollLeft=t*nz-x);}else if(e.shiftKey||Math.abs(e.deltaX)>Math.abs(e.deltaY)){e.preventDefault();suspendFollow();const unit=e.deltaMode===1?16:e.deltaMode===2?el.clientWidth:1;el.scrollLeft+=(e.shiftKey?(e.deltaY||e.deltaX):e.deltaX)*unit;}};el.addEventListener('wheel',wheel,{passive:false});return()=>el.removeEventListener('wheel',wheel);},[zoom]);

 const analyse=(id,file)=>{analysisQueue.current=analysisQueue.current.catch(()=>{}).then(async()=>{updateMedia(ms=>ms.map(m=>m.id===id?{...m,audioState:'analyzing'}:m));try{let m=mRef.current.find(m=>m.id===id);let serverId=m?.serverId;if(!serverId){serverId=(await api('media',file)).id;updateMedia(ms=>ms.map(m=>m.id===id?{...m,serverId}:m));}const data=await api('analyse',{id:serverId});updateMedia(ms=>ms.map(m=>m.id===id?{...m,...data,audioState:'ready'}:m));}catch(e){updateMedia(ms=>ms.map(m=>m.id===id?{...m,audioState:'failed',audioError:e.message}:m));}});};
 const fileLocation=file=>{const full=file.path||file.webkitRelativePath||'';const slash=Math.max(full.lastIndexOf('\\'),full.lastIndexOf('/'));return {sourcePath:full||undefined,sourceFolder:slash>0?full.slice(0,slash):undefined};};
 const relinkOne=async(id,file)=>{if(!file)return;const saved=pRef.current.media.find(x=>x.id===id);if(!saved)throw Error('Saved media item not found.');const url=URL.createObjectURL(file);try{const info=await mediaInfo(file,url);if(saved.type!==info.type||Math.abs((saved.duration||info.duration)-info.duration)>.1)throw Error(`${file.name} does not match the saved ${saved.name}.`);const loc=fileLocation(file),next={...saved,...info,size:file.size,lastModified:file.lastModified,...loc};updateMedia(ms=>[...ms.filter(x=>x.id!==id),{...next,url,file,audioState:next.type==='image'?'none':'queued'}]);commit(p=>({...p,media:p.media.map(x=>x.id===id?{...x,...info,size:file.size,lastModified:file.lastModified,...loc}:x)}),`Relinked ${saved.name}`);if(info.type!=='image')analyse(id,file);else {const im=new Image();im.src=url;await im.decode();}}catch(e){URL.revokeObjectURL(url);throw e;}};
 const importFiles=async(files)=>{if(exportRef.current)return;setImporting(true);try{for(const file of files){const url=URL.createObjectURL(file);let info;try{info=await mediaInfo(file,url);}catch(e){URL.revokeObjectURL(url);throw e;}const existing=pRef.current.media.find(m=>m.name===file.name&&m.size===file.size&&(!m.lastModified||m.lastModified===file.lastModified)&&!mRef.current.find(x=>x.id===m.id)?.url);const loc=fileLocation(file),m={id:existing?.id||T.uid('m'),name:file.name,size:file.size,lastModified:file.lastModified,...info,...loc};if(existing){URL.revokeObjectURL(url);await relinkOne(existing.id,file);continue;}updateMedia(ms=>[...ms.filter(x=>x.id!==m.id),{...m,url,file,audioState:m.type==='image'?'none':'queued'}]);commit(p=>({...p,media:[...p.media,m]}),'Media imported');if(m.type!=='image')analyse(m.id,file);else {const im=new Image();im.src=url;await im.decode();}setStatus(`Imported ${m.name}`);}}catch(e){fail(e);}finally{setImporting(false);fileInput.current.value='';}};
 const relinkFolder=async(files)=>{setImporting(true);let done=0;try{for(const saved of pRef.current.media.filter(m=>!m.sound&&!mRef.current.find(x=>x.id===m.id)?.url)){const candidate=files.find(f=>f.name.toLowerCase()===saved.name.toLowerCase()&&(!saved.size||f.size===saved.size));if(candidate){await relinkOne(saved.id,candidate);done++;}}setStatus(done?`Relinked ${done} media file${done===1?'':'s'} from selected folder.`:'No matching media found in selected folder.');}catch(e){fail(e);}finally{setImporting(false);relinkFolderInput.current.value='';}};
 const relinkSingle=async file=>{const id=relinkTarget.current;if(!id||!file)return;setImporting(true);try{await relinkOne(id,file);setStatus('Media relinked.');}catch(e){fail(e);}finally{setImporting(false);relinkTarget.current=null;singleRelinkInput.current.value='';}};
 const add=(id,trackId,start=timeRef.current)=>commit(p=>T.addMediaClip(p,id,trackId,start),'Clip added');
 const snap=(raw,ignore=[])=>{if(!snapping)return T.quant(Math.max(0,raw),project.fps);const pts=[0,timeRef.current,...pRef.current.clips.filter(c=>!ignore.includes(c.id)).flatMap(c=>[c.start,T.end(c)])],tol=10/zoom;const near=pts.sort((a,b)=>Math.abs(a-raw)-Math.abs(b-raw))[0];return T.quant(Math.max(0,Math.abs(near-raw)<tol?near:raw),project.fps);};
 const dragStart=(e,c)=>{if(e.target.closest('.gainLine,.resizeHandle')){e.preventDefault();return;}const ids=selectedIds.has(c.id)?selection():[c.id];dragRef.current={id:c.id,ids,offset:(e.clientX-e.currentTarget.getBoundingClientRect().left)/zoom};e.dataTransfer.setData('text/plain','clip:'+c.id);};
 const dragOver=(e,trackId)=>{e.preventDefault();const d=dragRef.current;if(!d)return;const c=project.clips.find(c=>c.id===d.id);const start=snap((e.clientX-e.currentTarget.getBoundingClientRect().left)/zoom-d.offset,[...E.expandedIds(project,d.ids)]);setGhost({trackId,start,duration:c.duration});};
 const drop=(e,trackId)=>{e.preventDefault();e.stopPropagation();const raw=e.dataTransfer.getData('text/plain'),t=(e.clientX-e.currentTarget.getBoundingClientRect().left)/zoom,d=dragRef.current;if(raw.startsWith('media:'))add(raw.slice(6),trackId,snap(t));else if(d)commit(p=>E.moveGroup(p,d.ids,d.id,trackId,snap(t-d.offset,[...E.expandedIds(p,d.ids)])),'Selection moved');dragRef.current=null;setGhost(null);};
 const editIds=()=>scope==='all'?project.clips.filter(c=>!project.tracks.find(t=>t.id===c.trackId).locked).map(c=>c.id):selection();
 const split=()=>commit(p=>{let next=p;const done=new Set();for(const id of editIds()){if(done.has(id))continue;for(const pair of T.pair(p,id))done.add(pair);next=T.splitClips(next,id,timeRef.current);}return next;},'Split '+(scope==='all'?'all unlocked tracks':'selection'));
 const trim=(edge,r)=>{const cs=project.clips.filter(c=>editIds().includes(c.id)&&c.start<timeRef.current&&T.end(c)>timeRef.current);if(!cs.length){setStatus('Place the playhead inside a target clip.');return;}const ranges=T.mergeRanges(cs.map(c=>edge==='left'?[c.start,timeRef.current]:[timeRef.current,T.end(c)]));if(commit(p=>E.scopedRemove(p,ranges,{scope,ids:selection(),ripple:r}),'Trimmed '+scope)){clearSelection();if(r&&edge==='left')seek(T.mapTime(timeRef.current,ranges));}};
 const globalTrimLeft=()=>{const t=timeRef.current;if(t<=0)return;pause();if(commit(p=>E.scopedRemove(p,[[0,t]],{scope,ids:selection(),ripple:true}),'Cropped left · '+scope)){clearSelection();seek(0);scroller.current.scrollLeft=0;}};
 const remove=()=>{if(selectedGap){deleteGap(selectedGap);return;}const ids=E.expandedIds(project,selection());if(!ids.size){setStatus('Select a clip or an empty gap first.');return;}if(commit(p=>({...p,clips:p.clips.filter(c=>!ids.has(c.id))}),'Selection deleted'))clearSelection();};
 const selectGap=(trackId,t)=>{const range=E.gapsOnTrack(pRef.current,trackId).find(([a,b])=>t>=a&&t<b);clearSelection();setGapMenu(null);if(range){setSelectedGap({trackId,range});setStatus('Gap selected · Delete closes it across all unlocked tracks');}return range;};
 const deleteGap=gap=>{const range=E.gapsOnTrack(pRef.current,gap.trackId).find(([a,b])=>Math.abs(a-gap.range[0])<T.EPS&&Math.abs(b-gap.range[1])<T.EPS);if(!range){setSelectedGap(null);setStatus('Gap changed; select it again.');return;}pause();const old=timeRef.current;if(commit(p=>E.deleteTimelineGap(p,gap),'Gap deleted · all unlocked tracks')){clearSelection();seek(T.mapTime(old,[range]));}setGapMenu(null);};

 const marquee=e=>{if(e.button!==0||e.target.closest('.ruler,.timelineMarker,.cutTarget,.resizeHandle,.gainLine')||(!boxMode&&e.target.closest('.clipBox')))return;
  e.preventDefault();if(boxMode)e.stopPropagation();const el=e.currentTarget,rect=el.getBoundingClientRect(),sx=e.clientX-rect.left,sy=e.clientY-rect.top,initial=e.shiftKey?selection():[];let moved=false;
  const move=ev=>{const bounds=scroller.current.getBoundingClientRect();if(ev.clientX>bounds.right-20)scroller.current.scrollLeft+=15;else if(ev.clientX<bounds.left+20)scroller.current.scrollLeft-=15;const r=el.getBoundingClientRect(),x=ev.clientX-r.left,y=ev.clientY-r.top;if(Math.abs(x-sx)+Math.abs(y-sy)<4)return;moved=true;setSelectedGap(null);const area={left:Math.min(x,sx),top:Math.min(y,sy),width:Math.abs(x-sx),height:Math.abs(y-sy)};setBox(area);const ids=new Set([...initial,...boxSelection(pRef.current,area,zoom)]);setSelectedIds(ids);setSelected([...ids][0]||null);};
  const up=()=>{suppressClick.current=moved;setBox(null);window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);window.removeEventListener('pointercancel',up);};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true});window.addEventListener('pointercancel',up,{once:true});
 };
 const panelResize=e=>{e.preventDefault();const sy=e.clientY,h=timelineHeight;const move=ev=>setTimelineHeight(T.clamp(h+sy-ev.clientY,200,window.innerHeight-260));const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true});};
 const resize=(e,c,edge)=>{e.stopPropagation();e.preventDefault();if(exportRef.current)return;const before=pRef.current;if(T.pair(before,c.id).some(id=>before.tracks.find(t=>t.id===before.clips.find(x=>x.id===id).trackId)?.locked)){setStatus('Unlock both linked tracks first.');return;}pause();const sx=e.clientX,original=edge==='left'?c.start:T.end(c);let target=original;const move=ev=>{target=T.quant(original+(ev.clientX-sx)/zoom,before.fps);setStatus(`${edge} edge → ${fmt(target)} (release to apply)`);};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);commit(p=>T.resizeClip(p,c.id,edge,target,ripple),'Clip resized');};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true});};
 const link=()=>{if(!clip)return;commit(p=>{if(clip.linkedId){const ids=T.pair(p,clip.id);return {...p,clips:p.clips.map(c=>ids.includes(c.id)?{...c,linkedId:null}:c)};}const type=p.tracks.find(t=>t.id===clip.trackId)?.type;const other=p.clips.find(c=>c.id!==clip.id&&!c.linkedId&&c.mediaId===clip.mediaId&&p.tracks.find(t=>t.id===c.trackId)?.type!==type&&Math.abs(c.start-clip.start)<T.EPS&&Math.abs(c.duration-clip.duration)<T.EPS&&Math.abs(c.sourceIn-clip.sourceIn)<T.EPS);if(!other)throw Error('Link requires matching source, start, in-point and duration.');return {...p,clips:p.clips.map(c=>c.id===clip.id?{...c,linkedId:other.id}:c.id===other.id?{...c,linkedId:clip.id}:c)};},'Link updated');};
 const referenceTrack=()=>selectedGap?.trackId||clip?.trackId||project.tracks.find(t=>!t.locked&&E.gapsOnTrack(project,t.id).length)?.id;
 const closeRanges=(ranges)=>{pause();const old=timeRef.current;if(commit(p=>E.scopedRemove(p,ranges,{scope,ids:selection(),ripple:true}),'Gaps closed · '+scope)){clearSelection();seek(T.mapTime(old,ranges));}setGapMenu(null);};
 const gaps=(all=false)=>{if(!all&&selectedGap){deleteGap(selectedGap);return;}const trackId=referenceTrack(),ranges=E.gapsOnTrack(project,trackId);const one=ranges.find(([a,b])=>timeRef.current>=a-T.EPS&&timeRef.current<=b+T.EPS);if(!ranges.length||!all&&!one){setStatus(all?'No gaps on reference track.':'Place the playhead in a gap, or right-click the gap.');return;}closeRanges(all?ranges:[one]);};
 const contextGap=(e,tr)=>{if(e.target.closest('.clipBox'))return;e.preventDefault();const t=(e.clientX-e.currentTarget.getBoundingClientRect().left)/zoom,range=selectGap(tr.id,t);if(range)setGapMenu({range,trackId:tr.id,x:Math.min(e.clientX,window.innerWidth-240),y:Math.min(e.clientY,window.innerHeight-110)});};
 const detect=()=>{if(!clip||!runtime?.levels?.length){setStatus('Wait for audio analysis, or retry it.');return;}const levels=runtime.levels,step=runtime.windowSec||.05,sourceEnd=clip.sourceIn+clip.duration;let start=null,rs=[];for(let i=0;i<=levels.length;i++){const silent=i<levels.length&&levels[i]<threshold;if(silent&&start===null)start=i*step;if(!silent&&start!==null){const a=Math.max(start,clip.sourceIn),b=Math.min(i*step,sourceEnd);if(b-a>=pauseLength){const lo=a+padding,hi=b-padding;if(hi-lo>=1/project.fps)rs.push([clip.start+lo-clip.sourceIn,clip.start+hi-clip.sourceIn]);}start=null;}}setPauses({clipId:clip.id,revision:project,ranges:T.mergeRanges(rs)});setStatus(`Detected ${rs.length} pauses. Review before removing.`);};
 const applyPauses=(mode,one=null)=>{if(!pauses||pauses.clipId!==selected||pauses.revision!==project){setStatus('Detect pauses again after editing or changing clips.');return;}const ranges=one?[one]:pauses.ranges;if(mode==='cuts'){commit(p=>{let next=p;for(const t of [...new Set(ranges.flat())].sort((a,b)=>b-a)){const target=next.clips.find(c=>c.trackId===clip.trackId&&c.start<t&&T.end(c)>t);if(target)next=T.splitClips(next,target.id,t);}return next;},'Cuts created');}else commit(p=>T.removeRanges(p,ranges,{ripple:mode==='ripple',ids:T.pair(p,selected)}),'Silence removed');clearSelection();};
 const addAdjustment=()=>commit(p=>{let n=T.addTrack(p,'adjustment');return {...n,clips:[...n.clips,{id:T.uid('adj'),kind:'adjustment',mediaId:null,trackId:n.tracks[0].id,start:T.quant(timeRef.current,p.fps),duration:5,sourceIn:0,name:'Adjustment layer',fx:T.fxDefault(),linkedId:null}]};},'Adjustment layer added');
 const marker=()=>commit(p=>({...p,markers:[...p.markers,{id:T.uid('marker'),time:T.quant(timeRef.current,p.fps),label:`Marker ${p.markers.length+1}`}]}),'Marker added');
 const openProject=async(file)=>{if(!file)return;try{const p=JSON.parse(await file.text());T.validate(p);pause();history.current.push(pRef.current);future.current=[];put(p);clearSelection();setPauses(null);seek(0);setStatus('Project opened. Relink missing media if requested.');}catch(e){fail(e);}projectInput.current.value='';};
 const newProject=()=>{if(project.clips.length&&!confirm('Start a new project? Save your current project first.'))return;pause();history.current.push(pRef.current);put(T.emptyProject());clearSelection();seek(0);setStatus('New project');};
 const autoKey=()=>{if(!clip)return;const src=renderer.current.sample(clip);if(!src){setStatus('Place the playhead inside the selected video.');return;}const pixels=src.getContext('2d').getImageData(0,0,src.width,src.height).data,green=[];for(let y=0;y<src.height;y+=4)for(let x=0;x<src.width;x+=4){if(x>src.width*.2&&x<src.width*.8&&y>src.height*.15)continue;const i=(y*src.width+x)*4,r=pixels[i],g=pixels[i+1],b=pixels[i+2];if(g>r*1.3&&g>b*1.3&&g>20)green.push([r,g,b]);}if(green.length<10){setStatus('No clear green area found. Use Pick colour.');return;}const rgb=[0,1,2].map(k=>green.map(x=>x[k]).sort((a,b)=>a-b)[Math.floor(green.length/2)]);changeFx(clip.id,'chroma','key','#'+rgb.map(x=>x.toString(16).padStart(2,'0')).join(''));changeFx(clip.id,'chroma','enabled',true);};
 const pick=e=>{if(!picking||!clip)return;const src=renderer.current.sample(clip);if(!src)return;const r=canvas.current.getBoundingClientRect(),tr=clip.fx.transform,aspect=src.width/src.height,pa=project.width/project.height,fw=aspect>pa?1:aspect/pa,fh=aspect>pa?pa/aspect:1;const u=((e.clientX-r.left)/r.width-.5-tr.x/250)/(fw*tr.scale/100)+.5,v=((e.clientY-r.top)/r.height-.5-tr.y/250)/(fh*tr.scale/100)+.5;if(u<0||u>1||v<0||v>1)return;const rgb=src.getContext('2d').getImageData(Math.min(src.width-1,Math.floor(u*src.width)),Math.min(src.height-1,Math.floor(v*src.height)),1,1).data;changeFx(clip.id,'chroma','key','#'+[...rgb].slice(0,3).map(x=>x.toString(16).padStart(2,'0')).join(''));changeFx(clip.id,'chroma','enabled',true);setPicking(false);};
 const chooseOutput=async()=>{try{if(window.rancut?.desktop)setOutputFolder(await window.rancut.chooseOutputFolder());else setOutputFolder((await api('output',{directory:outputFolder})).directory);}catch(e){setExportError(e.message);}};
 const cancelExport=()=>{cancelRef.current=true;exportAbort.current?.abort();setExportStage('Cancelling…');};
 useEffect(()=>{if(!exporting)return;const timer=setInterval(()=>setElapsed((performance.now()-exportBegan.current)/1000),1000);return()=>clearInterval(timer);},[exporting]);
 useEffect(()=>window.rancut?.onPrepareClose(async()=>{pause();cancelRef.current=true;exportAbort.current?.abort();await saveRecovery(pRef.current).catch(()=>{});}),[]);
 const exportVideo=async()=>{if(!duration||exportRef.current)return;if(missing.length){setExportError('Relink all media before exporting.');return;}pause();exportRef.current=true;setExporting(true);cancelRef.current=false;setProgress(0);setResult(null);setExportError('');setExportStage('Preparing audio…');setElapsed(0);exportBegan.current=performance.now();const controller=exportAbort.current=new AbortController();let job;const p=C.withTransitionAudio(structuredClone(pRef.current)),oldTime=timeRef.current;try{
  const chosenOutput=await api('output',{directory:outputFolder},controller.signal);setOutputFolder(chosenOutput.directory);
  while(renderer.current.drawing){if(controller.signal.aborted)throw Error('Export cancelled.');await sleep(20);}
  const audio=p.clips.filter(c=>p.tracks.find(t=>t.id===c.trackId)?.type==='audio'&&!p.tracks.find(t=>t.id===c.trackId)?.muted),exportSources=new Map();
  for(const c of audio){if(controller.signal.aborted)throw Error('Export cancelled.');if(exportSources.has(c.mediaId))continue;const meta=p.media.find(m=>m.id===c.mediaId),m=meta?.sound?soundRuntime(meta):mRef.current.find(m=>m.id===c.mediaId);if(!m?.file)throw Error('Audio source missing. Relink media.');const serverId=m.serverId||(await api('media',m.file,controller.signal)).id;exportSources.set(c.mediaId,serverId);if(!meta.sound)updateMedia(ms=>ms.map(x=>x.id===m.id?{...x,serverId}:x));}
  const frames=Math.max(1,Math.ceil(T.duration(p)*p.fps-T.EPS)),height=Math.round(exportWidth*p.height/p.width/2)*2;
  job=(await api('export',{width:exportWidth,height,fps:p.fps,frames,frameFormat:'jpeg',quality,encoder:encoderInfo.selected,audio:audio.map(c=>({serverId:exportSources.get(c.mediaId),start:c.start,duration:c.duration,sourceIn:c.sourceIn,gainDb:c.fx?.gainDb??0,fadeMs:c.fx?.fadeMs??5}))},controller.signal)).id;exportJob.current=job;
  let report=0;
  for(let n=0;n<frames;n++){
   if(controller.signal.aborted)throw Error('Export cancelled.');await renderer.current.draw(p,mRef.current,n/p.fps,{width:exportWidth,exact:true});await api(`export/${job}/frame?index=${n}`,await renderer.current.captureJPEG(.97),AbortSignal.any([controller.signal,AbortSignal.timeout(60000)]));
   if(performance.now()-report>200||n===frames-1){setProgress(Math.round((n+1)/frames*92));setExportStage(`Rendering frame ${n+1} / ${frames}`);report=performance.now();await sleep(0);}
  }
  setExportStage('Mixing sound and saving MP4…');await api(`export/${job}/finish`,{},controller.signal);
  for(;;){if(controller.signal.aborted)throw Error('Export cancelled.');const state=await api(`export/${job}/status`,undefined,controller.signal);if(state.state==='failed')throw Error(state.error);if(state.state==='complete'){setResult(state.savedPath);setOutputFolder(state.outputDirectory);break;}await sleep(300);}
  setProgress(100);setExportStage('Saved successfully');setStatus('Export saved automatically in '+outputFolder);
 }catch(e){if(job)await api(`export/${job}/cancel`,{}).catch(()=>{});const message=controller.signal.aborted?'Export cancelled. No incomplete MP4 was published.':e.message;setExportError(message);setExportStage('');setStatus(message);}finally{exportRef.current=false;exportJob.current=null;setExporting(false);seek(oldTime);}};
 useEffect(()=>{const key=e=>{if(exportRef.current||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;const k=e.key.toLowerCase();if((e.ctrlKey||e.metaKey)&&k==='a'){e.preventDefault();selectAll();return;}if(k==='escape'){clearSelection();setGapMenu(null);return;}if((e.ctrlKey||e.metaKey)&&k==='s'){e.preventDefault();downloadJSON(pRef.current);return;}if((e.ctrlKey||e.metaKey)&&k==='z'){e.preventDefault();e.shiftKey?redo():undo();return;}if((e.ctrlKey||e.metaKey)&&k==='y'){e.preventDefault();redo();return;}const actions={' ':toggle,x:split,z:globalTrimLeft,c:()=>trim('right',false),q:()=>trim('left',true),w:()=>trim('right',true),g:()=>gaps(false),l:link,m:marker,delete:remove,backspace:remove,arrowleft:()=>{pause();seek(timeRef.current-1/project.fps);},arrowright:()=>{pause();seek(timeRef.current+1/project.fps);},f:toggleFullscreen};if(actions[k]){e.preventDefault();actions[k]();}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);});
 useEffect(()=>{setSelectedGap(null);setGapMenu(null);const live=new Set(project.clips.map(c=>c.id));setSelectedIds(ids=>new Set([...ids].filter(id=>live.has(id))));setSelected(id=>live.has(id)?id:null);},[project]);
 const tickStep=[.1,.5,1,5,10,30,60,120,300,600,1800,3600].find(n=>n*zoom>=65)||3600,tickStart=Math.floor(scroll/zoom/tickStep)*tickStep;
 const cfx=clip?.fx||T.fxDefault(),afx=project.clips.find(c=>c.id===audioId())?.fx;
 return <div className="app">
  <header className="topbar"><div className="brand"><b>RanCut</b><span>LOCAL EDITOR · v0.4.2</span></div><div className="topActions"><span className={'gpuStatus '+(encoderInfo.mode==='gpu'?'gpuOn':'')} title="Export encoder">{encoderInfo.mode==='gpu'?`${encoderInfo.selected} active`:'CPU encoder'}</span><button onClick={()=>setShowMedia(!showMedia)}>Media {showMedia?"−":"+"}</button><button onClick={()=>setShowInspector(!showInspector)}>Inspector {showInspector?"−":"+"}</button><button disabled={exporting} onClick={newProject}>New</button><button disabled={exporting} onClick={()=>projectInput.current.click()}><FolderOpen/>Open</button><button disabled={exporting} onClick={()=>downloadJSON(project)}><Save/>Save</button><button className="iconBtn" disabled={exporting} onClick={undo} title="Undo"><Undo2/></button><button className="iconBtn" disabled={exporting} onClick={redo} title="Redo"><Redo2/></button><button className="exportBtn" disabled={!duration||exporting} onClick={()=>setExportOpen(true)}><Download/>Export</button></div><input ref={projectInput} type="file" hidden accept=".json" onChange={e=>openProject(e.target.files[0])}/></header>
  <div className="statusBar" role="status"><span>{status}</span><span>{ready?'Autosave enabled':'Loading…'} · {project.width}×{project.height} · {project.fps} fps</span></div>
  {!!missing.length&&<div className="missingBanner">{missing.length} source file(s) need reconnecting. <button disabled={importing} onClick={()=>relinkFolderInput.current.click()}>Relink source folder</button> <button disabled={importing} onClick={()=>fileInput.current.click()}>Choose files manually</button></div>}
  <div style={{gridTemplateColumns:`${showMedia?"220px":"0px"} minmax(240px,1fr) ${showInspector?"280px":"0px"}`,gridTemplateRows:`minmax(160px,1fr) ${timelineHeight}px`}} className={`editorGrid ${exporting?'busyEditor':''}`}>
   <aside className="leftPanel" style={{display:showMedia?undefined:"none"}}><div className="tabs">{['media','creator','effects','markers'].map(x=><button key={x} className={leftTab===x?'active':''} onClick={()=>setLeftTab(x)}>{x}</button>)}</div><input ref={fileInput} type="file" hidden multiple accept="video/*,audio/*,image/*,.mov,.mkv" onChange={e=>importFiles([...e.target.files])}/><input ref={relinkFolderInput} type="file" hidden multiple webkitdirectory="true" directory="true" onChange={e=>relinkFolder([...e.target.files])}/><input ref={singleRelinkInput} type="file" hidden accept="video/*,audio/*,image/*,.mov,.mkv" onChange={e=>relinkSingle(e.target.files[0])}/>
    {leftTab==='media'?<><button className="importBox" disabled={importing} onClick={()=>fileInput.current.click()}><Upload/><b>{importing?'Importing…':'Import / relink media'}</b><small>Video · image · audio</small></button><div className="mediaHint">Drop into an empty area. Add a video track for a background, person, logo or B-roll.</div><div className="mediaList">{project.media.map(m=>{const r=media.find(x=>x.id===m.id);return <div key={m.id} className="mediaCard" draggable onDragStart={e=>e.dataTransfer.setData('text/plain','media:'+m.id)} onDoubleClick={()=>add(m.id,project.tracks.find(t=>t.type===(m.type==='audio'?'audio':'video'))?.id)}><div className="mediaIcon">{m.type==='image'?<ImageIcon/>:m.type==='audio'?<Music/>:<Film/>}</div><div className="mediaMeta"><b>{m.name}</b><span>{!r?.url&&!m.sound?<>MISSING · <button className="miniRelink" onClick={()=>{relinkTarget.current=m.id;singleRelinkInput.current.click();}}>Choose file</button></>:`${fmt(m.duration)} · ${r?.audioState||m.type}`}</span>{m.sourcePath&&<small title={m.sourcePath}>{m.sourcePath}</small>}</div></div>;})}</div></>:leftTab==='creator'?<CreatorPanel project={project} clip={clip} commit={commit} fail={fail} seek={seek}/>:leftTab==='effects'?<div className="effectsList"><button className="wideBtn" onClick={addAdjustment}>+ Adjustment layer</button><div><b>Chroma key</b><span>Select a video, then use Chroma. Off by default for new clips.</span></div><div><b>Logos and B-roll</b><span>Add Video Track. Higher tracks appear above lower tracks.</span></div><div><b>Audio / SFX</b><span>Import music or sound effects onto another audio track. All unmuted tracks mix.</span></div></div>:<><button className="wideBtn" onClick={marker}>+ Marker at playhead (M)</button>{project.markers.map(m=><div className="markerRow" key={m.id}><button onClick={()=>seek(m.time)}>{m.label} · {fmt(m.time)}</button><button onClick={()=>commit(p=>({...p,markers:p.markers.filter(x=>x.id!==m.id)}),'Marker deleted')}>×</button></div>)}</>}
    <details className="projectSettings"><summary>Project format</summary><label>Canvas<select aria-label="Project canvas" value={`${project.width}x${project.height}`} onChange={e=>{const [width,height]=e.target.value.split('x').map(Number);commit(p=>({...p,width,height}),'Canvas updated');}}><option value="1920x1080">16:9 landscape</option><option value="1080x1920">9:16 portrait</option><option value="1080x1080">1:1 square</option></select></label><label>FPS<select aria-label="Project FPS" value={project.fps} disabled={!!project.clips.length} onChange={e=>commit(p=>({...p,fps:+e.target.value}),'FPS updated')}>{[24,25,30,50,60].map(n=><option key={n}>{n}</option>)}</select></label><small>Set FPS before adding clips. Canvas stays fixed across cuts.</small></details>
   </aside>
   <section className="viewerPanel"><div className={`viewer ${picking?'picking':''}`} ref={viewer}><canvas ref={canvas} onClick={pick}/>{!project.clips.length&&<div className="viewerEmpty"><Film/><b>Start with your footage</b><span>Import a clip and drag it onto V1</span></div>}<button className="fullscreen" title={fullScreen?"Exit fullscreen":"Fullscreen"} onClick={toggleFullscreen}>{fullScreen?"Exit":<Maximize2/>}</button>{picking&&<div className="pickTip">Click green on the selected subject</div>}</div><div className="transport"><select aria-label="Preview quality" title="Preview render resolution; export is independent" value={previewScale} onChange={e=>setPreviewScale(+e.target.value)}><option value="1">Full</option><option value="0.5">Half</option><option value="0.25">Quarter</option></select><button onClick={toggle} title="Play / pause">{playing?<Pause/>:<Play/>}</button><span>{fmt(time)}</span><input aria-label="Playhead" type="range" min="0" max={Math.max(duration,.01)} step={1/project.fps} value={time} onChange={e=>seek(+e.target.value)}/><span>{fmt(duration)}</span><div className="audioMeter" title={`Master peak ${meter.toFixed(1)} dBFS`}><i style={{width:`${(meter+60)/60*100}%`,background:meter>-.5?'#fa7979':'#7cdba4'}}/></div></div></section>
   <aside className="inspector" style={{display:showInspector?undefined:"none"}}><div className="inspectorHead"><b>Inspector</b><span>{clip?.trackId||'Select a clip'}</span></div>{clip?<><div className="insTabs">{['video','color','chroma','audio'].map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</div><div className="clipName">{clip.name}<small>{fmt(clip.start)} – {fmt(T.end(clip))}</small></div><div className="effectTransfer"><select aria-label="Effects to paste" value={effectSection} onChange={e=>setEffectSection(e.target.value)}><option value="all">All visual effects</option><option value="chroma">Chroma</option><option value="color">Colour</option><option value="transform">Position / scale</option></select><button onClick={()=>{setCopiedFx(structuredClone(cfx));setStatus("Effects copied");}}>Copy</button><button disabled={!copiedFx||!selectedIds.size} onClick={pasteFx}>Paste ({selectedIds.size})</button></div><div className="insBody">
    {tab==='video'&&clip.fx?.scene&&<StyleClipControls clip={clip} changeFx={changeFx} commit={commit}/>}
    {tab==='video'&&!clip.fx?.scene&&<>{[['Scale','scale',25,200],['Position X','x',-100,100],['Position Y','y',-100,100],['Opacity','opacity',0,100]].map(([n,k,a,b])=><Slider key={k} name={n} min={a} max={b} value={cfx.transform[k]} onChange={v=>changeFx(clip.id,'transform',k,v)}/>)}<Slider name="Layer blur" value={cfx.blur||0} max={20} onChange={v=>changeFx(clip.id,null,'blur',v)}/></>}
    {tab==='color'&&[['Exposure','exposure',-2,2,.05],['Contrast','contrast',-100,100,1],['Saturation','saturation',0,200,1],['Temperature','temp',-100,100,1],['Tint','tint',-100,100,1]].map(([n,k,a,b,step])=><Slider key={k} name={n} min={a} max={b} step={step} value={cfx.color[k]} onChange={v=>changeFx(clip.id,'color',k,v)}/>)}
    {tab==='chroma'&&<><label className="toggleRow">Enable green-screen key<input type="checkbox" checked={cfx.chroma.enabled} onChange={e=>changeFx(clip.id,'chroma','enabled',e.target.checked)}/></label><label className="colorRow">Screen colour<input type="color" value={cfx.chroma.key} onChange={e=>changeFx(clip.id,'chroma','key',e.target.value)}/></label><div className="twoBtns"><button onClick={autoKey}>Auto sample</button><button onClick={()=>setPicking(v=>!v)}>{picking?'Cancel pick':'Pick colour'}</button></div>{[['Subject protection','threshold',0,.7],['Key range','softness',.02,.85],['Edge choke','choke',0,1],['Edge feather','feather',0,2],['Despill','spill',0,1],['Edge colour cleanup','decontam',0,1]].map(([n,k,a,b])=><Slider key={k} name={n} value={cfx.chroma[k]} min={a} max={b} step={.01} onChange={v=>changeFx(clip.id,'chroma',k,v)}/>)}<label className="toggleRow">View matte<input type="checkbox" checked={cfx.chroma.matte} onChange={e=>changeFx(clip.id,'chroma','matte',e.target.checked)}/></label><small>Green-screen engine. Preview and MP4 export use the same renderer.</small></>}
    {tab==='audio'&&<><Slider name="Cut fade" value={afx?.fadeMs??5} min={0} max={20} suffix=" ms" onChange={v=>{if(audioId())changeFx(audioId(),null,'fadeMs',v);}}/>{audioId()?<Slider name="Gain" value={afx?.gainDb??0} min={-60} max={12} step={.1} suffix=" dB" onChange={v=>changeFx(audioId(),null,'gainDb',v)}/>:<p>No linked audio. Select an audio clip.</p>}<div className="analysisState"><span>Waveform</span><b>{runtime?.audioState||'Missing media'}</b></div>{runtime?.audioState==='failed'&&<button className="wideBtn secondary" onClick={()=>analyse(runtime.id,runtime.file)}>Retry audio analysis</button>}<Slider name="Silence threshold" value={threshold} min={-65} max={-15} onChange={setThreshold} suffix=" dB"/><label className="numRow">Minimum pause<input aria-label="Minimum pause" type="number" min=".1" max="10" step=".05" value={pauseLength} onChange={e=>setPauseLength(T.clamp(+e.target.value,.1,10))}/>s</label><label className="numRow">Keep speech padding<input aria-label="Speech padding" type="number" min="0" max="1" step=".01" value={padding} onChange={e=>setPadding(T.clamp(+e.target.value,0,1))}/>s</label><button className="wideBtn" onClick={detect}>Detect pauses</button>{pauses&&<><div className="pauseSummary">{pauses.ranges.length} pauses · {pauses.ranges.reduce((s,[a,b])=>s+b-a,0).toFixed(2)}s</div><div className="pauseActions"><button onClick={()=>applyPauses('cuts')}>Make cuts</button><button onClick={()=>applyPauses('remove')}>Remove, keep gaps</button><button className="primary" onClick={()=>applyPauses('ripple')}>Remove + ripple all tracks</button></div><div className="pauseList">{pauses.ranges.map(([a,b],i)=><div className="pauseRow" key={i}><span onClick={()=>seek(a)}>{fmt(a)}–{fmt(b)}</span><button onClick={()=>applyPauses('ripple',[a,b])}>Remove</button><button onClick={()=>setPauses({...pauses,ranges:pauses.ranges.filter((_,n)=>n!==i)})}>Keep</button></div>)}</div></>}</>}
   </div><div className="insFooter"><button onClick={()=>commit(p=>({...p,clips:p.clips.map(c=>c.id===clip.id?{...c,fx:T.fxDefault()}:c)}),'Effects reset')}>Reset effects</button><button className="danger" onClick={remove}>Delete</button></div></>:<div className="noSelection">Select a timeline clip</div>}</aside>
   <section className="timelinePanel"><div className="panelDivider" role="separator" aria-label="Resize timeline" aria-orientation="horizontal" tabIndex="0" onPointerDown={panelResize} onKeyDown={e=>{if(["ArrowUp","ArrowDown"].includes(e.key)){e.preventDefault();e.stopPropagation();setTimelineHeight(h=>T.clamp(h+(e.key==="ArrowUp"?20:-20),200,window.innerHeight-260));}}}/><div className="timelineToolbar"><div className="editBtns"><button onClick={split}><Scissors/>Split <kbd>X</kbd></button><button onClick={globalTrimLeft}>Crop left <kbd>Z</kbd></button><button onClick={()=>trim('right',false)}>Trim R <kbd>C</kbd></button><button onClick={()=>trim('left',true)}>Ripple L <kbd>Q</kbd></button><button onClick={()=>trim('right',true)}>Ripple R <kbd>W</kbd></button><button onClick={()=>gaps(false)}>Close gap</button><button onClick={()=>gaps(true)}>Close all gaps</button><button className={boxMode?"active":""} onClick={()=>setBoxMode(!boxMode)}>Box select {boxMode?"ON":"OFF"}</button><button onClick={selectAll}>Select all</button><button disabled={!clip} onClick={selectToEnd}>From clip → end</button><button onClick={clearSelection}>Clear</button><button onClick={remove}>Delete</button><button className={ripple?'active':''} onClick={()=>setRipple(!ripple)}>Ripple {ripple?'ON':'OFF'}</button><button onClick={link}><Link2/>{clip?.linkedId?'Unlink':'Link'}</button><button className={follow?'active':''} onClick={()=>{setFollow(v=>!v);setFollowSuspended(false);clearTimeout(followTimer.current);}}>Follow {follow?(followSuspended?'ON · paused':'ON'):'OFF'}</button></div><div className="zoomCtl"><input aria-label="Timeline zoom" type="range" min="0" max="100" value={Math.log(zoom/MIN_ZOOM)/Math.log(2400/MIN_ZOOM)*100} onChange={e=>{setZoom(MIN_ZOOM*(2400/MIN_ZOOM)**(+e.target.value/100));}}/><button onClick={()=>{setFollowSuspended(false);setZoom(fitZoom(viewport,displayDuration));scroller.current.scrollLeft=0;}}>Fit</button></div></div>
    <div className="trackToolbar"><select aria-label="Editing scope" value={scope} onChange={e=>setScope(e.target.value)}><option value="all">All unlocked tracks</option><option value="selected">Selected + linked clips</option></select><button className={snapping?"active":""} onClick={()=>setSnapping(!snapping)}>Snap {snapping?"ON":"OFF"}</button><select aria-label="Add track" value="" onChange={e=>{if(e.target.value)commit(p=>T.addTrack(p,e.target.value),'Track added');}}><option value="">+ Add track</option><option value="video">Video / overlay</option><option value="audio">Audio</option><option value="adjustment">Adjustment</option></select><span>{selectedIds.size} selected · Shift-click or drag empty space · Gaps: {referenceTrack()||"choose track"}</span></div>
    <div className="timelineBody"><div className="trackLabels" ref={labels}><div className="rulerLabel">TRACKS</div>{project.tracks.map(tr=><div className={`trackLabel ${tr.type==='audio'?'audioLabel':''}`} key={tr.id}><b title={tr.name||tr.id}>{tr.name||tr.id}</b><button title={tr.type==='audio'?'Mute track':'Hide track'} onClick={()=>commit(p=>({...p,tracks:p.tracks.map(t=>t.id===tr.id?{...t,[tr.type==='audio'?'muted':'hidden']:!t[tr.type==='audio'?'muted':'hidden']}:t)}),'Track updated')}>{tr.type==='audio'?(tr.muted?<VolumeX/>:<Volume2/>):(tr.hidden?<EyeOff/>:<Eye/>)}</button><button title="Lock track" onClick={()=>commit(p=>({...p,tracks:p.tracks.map(t=>t.id===tr.id?{...t,locked:!t.locked}:t)}),'Track lock updated')}>{tr.locked?<Lock/>:<Unlock/>}</button><button title="Remove empty track" disabled={tr.locked||project.clips.some(c=>c.trackId===tr.id)} onClick={()=>commit(p=>({...p,tracks:p.tracks.filter(t=>t.id!==tr.id)}),'Empty track removed')}>×</button></div>)}</div>
     <div className="timelineScroller" ref={scroller} onPointerDown={e=>{if(e.target===e.currentTarget)suspendFollow();}} onScroll={e=>{setScroll(e.currentTarget.scrollLeft);labels.current.scrollTop=e.currentTarget.scrollTop;}}>
      <div className="timelineCanvas" onPointerDownCapture={marquee} style={{width:timelineWidth,minHeight:30+project.tracks.reduce((s,t)=>s+(t.type==='audio'?80:50),0)}} onClick={e=>{if(suppressClick.current){suppressClick.current=false;return;}if(e.target.closest('.clipBox'))return;const rect=e.currentTarget.getBoundingClientRect(),t=(e.clientX-rect.left)/zoom,lane=e.target.closest('[data-track]');if(lane)selectGap(lane.dataset.track,t);else setSelectedGap(null);seek(t);}}><div className="ruler">{Array.from({length:Math.ceil(viewport/zoom/tickStep)+2},(_,i)=>tickStart+i*tickStep).filter(t=>t<=displayDuration).map(t=><div className="tick" key={t} style={{left:t*zoom}}><i/><span>{fmt(t)}</span></div>)}</div>
       {project.tracks.map(tr=><div key={tr.id} data-track={tr.id} className={`lane ${tr.type==='audio'?'audioLane':''} ${tr.locked?'locked':''}`} onContextMenu={e=>contextGap(e,tr)} onDragOver={e=>dragOver(e,tr.id)} onDrop={e=>drop(e,tr.id)}>{project.clips.filter(c=>c.trackId===tr.id&&T.end(c)*zoom>=scroll-100&&c.start*zoom<=scroll+viewport+100).map(c=><div key={c.id} data-clip={c.id} className={`clipBox ${tr.type==='audio'?'audioTrack':project.media.find(m=>m.id===c.mediaId)?.type||'adjustment'} ${selectedIds.has(c.id)?'selected':''}`} style={{left:c.start*zoom,width:Math.max(1,c.duration*zoom)}} draggable={!tr.locked&&!boxMode} onDragStart={e=>dragStart(e,c)} onDragEnd={()=>{dragRef.current=null;setGhost(null);}} onMouseDown={e=>{e.stopPropagation();choose(c.id,e.shiftKey||e.ctrlKey||e.metaKey);}} title={`${c.name} · ${fmt(c.start)} – ${fmt(T.end(c))}`}><div className="resizeHandle left" onPointerDown={e=>resize(e,c,'left')}/><div className="resizeHandle right" onPointerDown={e=>resize(e,c,'right')}/>{tr.type==='audio'&&<Waveform clip={c} media={project.media.find(m=>m.id===c.mediaId)?.sound?soundRuntime(project.media.find(m=>m.id===c.mediaId)):media.find(m=>m.id===c.mediaId)} zoom={zoom} scroll={scroll} viewport={viewport} onGain={v=>changeFx(c.id,null,'gainDb',v)}/>}<div className="clipTop" style={{paddingLeft:Math.max(6,scroll-c.start*zoom+6)}}><span>{tr.type==='audio'?<Music/>:<Film/>}</span><b>{c.name}</b>{c.linkedId&&<Link2/>}</div></div>)}{tr.type==='video'&&C.cutPairs(project,tr.id).map(({right})=><button key={'cut_'+right.id} className={`cutTarget ${right.transition?'hasTransition':''}`} style={{left:right.start*zoom-7}} title={right.transition?right.transition.name+' · click to edit':'Cut · drop transition here'} onPointerDown={e=>e.stopPropagation()} onClick={e=>{e.stopPropagation();clearSelection();choose(right.id);setLeftTab('creator');}} onDragOver={e=>e.preventDefault()} onDrop={e=>{const raw=e.dataTransfer.getData('rancut-transition');if(!raw)return;e.preventDefault();e.stopPropagation();try{const preset=C.validateTransition(JSON.parse(raw));commit(p=>C.attachTransition(p,right.id,preset),'Transition applied');}catch(err){fail(err);}}}>{right.transition?'◆':'+'}</button>)}{selectedGap?.trackId===tr.id&&<div className="selectedGap" style={{left:selectedGap.range[0]*zoom,width:(selectedGap.range[1]-selectedGap.range[0])*zoom}}><span>Gap · Delete to close</span></div>}{ghost?.trackId===tr.id&&<div className="dropGhost" style={{left:ghost.start*zoom,width:ghost.duration*zoom}}/>}{pauses&&clip?.trackId===tr.id&&pauses.ranges.map(([a,b],i)=><div key={i} className="pauseMark" style={{left:a*zoom,width:(b-a)*zoom}}/>)}</div>)}
       {box&&<div className="selectionBox" style={box}/>} {project.markers.map(m=><div key={m.id} className="timelineMarker" style={{left:m.time*zoom}} title={m.label}><i/></div>)}<div className="playhead" style={{left:time*zoom}}><i/></div>
      </div>
     </div>
    </div><div className="timelineFoot"><span>Z crop left · Scope above · Ctrl+A select all · Esc clear · Ctrl+Z undo</span><span>{project.clips.length} clips · {fmt(duration)}</span></div>
   </section>
  </div>
  {gapMenu&&<div className="gapContext" style={{left:gapMenu.x,top:gapMenu.y}}><b>{gapMenu.trackId}: {fmt(gapMenu.range[0])}–{fmt(gapMenu.range[1])}</b><small>All unlocked tracks</small><button onClick={()=>deleteGap(gapMenu)}>Ripple delete this gap</button><button onClick={()=>setGapMenu(null)}>Cancel</button></div>}
  {exportOpen&&<div className="modalShade"><div className="exportModal"><div className="modalHead"><div><b>Export MP4</b><span>Frames rendered locally, with mixed audio</span></div><button disabled={exporting} onClick={()=>setExportOpen(false)}>×</button></div><div className="exportGrid"><label>Output width<select disabled={exporting} value={exportWidth} onChange={e=>setExportWidth(+e.target.value)}>{[1280,1920,2560,3840].map(w=><option key={w} value={w}>{w} px</option>)}</select></label><label>Quality<select disabled={exporting} value={quality} onChange={e=>setQuality(e.target.value)}>{['Good','High','Maximum'].map(q=><option key={q}>{q}</option>)}</select></label></div><div className="outputFolder"><label>Auto-save output folder<input aria-label="Output folder" disabled={exporting} readOnly={!!window.rancut?.desktop} value={outputFolder} onChange={e=>setOutputFolder(e.target.value)}/></label><button disabled={exporting} onClick={chooseOutput}>{window.rancut?.desktop?"Choose folder…":"Set folder"}</button></div><div className="exportNote">{exportWidth}×{Math.round(exportWidth*project.height/project.width/2)*2} · {project.fps} fps · {encoderInfo.mode==='gpu'?encoderInfo.selected+' GPU':'CPU'} H.264 / AAC. MP4 saves automatically to the folder above. Rendering can continue with the app minimised. {ffmpeg?'':'Local FFmpeg is unavailable — reinstall dependencies.'}</div>{exporting&&<div className="progress"><i style={{width:progress+'%'}}/><span>{progress}%</span></div>}<div className="exportStatus" role="status">{exportStage}{elapsed>0&&<small>Elapsed {Math.floor(elapsed/60)}m {Math.floor(elapsed%60)}s{exporting&&progress>0&&progress<92?` · estimated ${Math.ceil(elapsed*(92-progress)/progress/60)}m rendering left`:""}</small>}</div>{exportError&&<p className="exportError" role="alert">{exportError}</p>}{result&&<div className="downloadResult">Saved: {result}{window.rancut?.desktop&&<button onClick={()=>window.rancut.openOutputFolder().catch(e=>setExportError(e.message))}>Open output folder</button>}</div>}<div className="modalActions">{exporting?<button onClick={cancelExport}>Cancel export</button>:<button className="primaryExport" disabled={!ffmpeg||!duration} onClick={exportVideo}>Export timeline</button>}</div></div></div>}
 </div>;
}
createRoot(document.getElementById('root')).render(<App/>);
