import React,{useState} from 'react';
import {projectOrder} from './project-store.js';
export default function ProjectHome({items=[],busy=false,error='',onNew,onOpen,onImport,onEdit,onDuplicate,onRecover,onResume,onHelp,onTrashBatch}){
 const [query,setQuery]=useState(''),[name,setName]=useState(''),[trash,setTrash]=useState(false),[recover,setRecover]=useState(null),[renaming,setRenaming]=useState(null),[draft,setDraft]=useState('');
 const [selected,setSelected]=useState([]);
 const batch=action=>{const ids=selected.filter(id=>items.some(x=>x.id===id&&x.deleted&&!x.purged));if(!ids.length)return;if(action==='delete'&&!confirm('Permanently delete '+ids.length+' project(s) and their recovery copies? Original media files will stay untouched.'))return;onTrashBatch?.(ids,action);setSelected([]);};
 const shown=projectOrder(items,query,trash);
 return <section className="projectHome" aria-label="Project home"><header><div className="homeBrand"><img src="./brand-icon.png" alt="RanCut icon"/><div><h1>RanCut</h1><span>Your next story starts here.</span></div></div><div><button onClick={onHelp}>Help & About</button>{onResume&&<button onClick={onResume}>Back to editor</button>}</div></header>
 <div className="homeIntro"><div><h2>Make something worth watching.</h2><p>All your local projects, ready when you are.</p></div><form onSubmit={e=>{e.preventDefault();if(name.trim())onNew(name.trim());}}><input aria-label="New project name" placeholder="Name your new project" maxLength={100} value={name} onChange={e=>setName(e.target.value)}/><button className="primary" disabled={busy||!name.trim()}>+ New project</button><button type="button" disabled={busy} onClick={onImport}>Open project file</button></form></div>
 <div className="homeFilters"><h2>{trash?'Trash':'Your projects'}</h2><input aria-label="Search projects" placeholder="Search projects…" value={query} onChange={e=>setQuery(e.target.value)}/><button onClick={()=>{setTrash(!trash);setRecover(null);setSelected([]);}}>{trash?'Your projects':'Trash'}</button></div>
 {trash&&<div className="trashActions"><label><input aria-label="Select all trashed projects" type="checkbox" checked={shown.length>0&&shown.every(x=>selected.includes(x.id))} onChange={e=>setSelected(e.target.checked?shown.map(x=>x.id):[])}/> Select all</label><span>{selected.length} selected</span><button disabled={busy||!selected.length} onClick={()=>batch('restore')}>Restore selected</button><button className="danger" disabled={busy||!selected.length} onClick={()=>batch('delete')}>Delete permanently</button></div>}<p className="homeNote">Projects autosave on this computer. Save a project file for your own backup. Source videos stay in their original folders.</p>{error&&<p role="alert" className="exportError">{error}</p>}{busy&&<p role="status">Saving / loading project…</p>}
 <div className="projectGrid">{shown.map(item=><article className={'projectCard '+(item.pinned?'isPinned':'')} key={item.id}>{trash&&<label className="trashSelect"><input type="checkbox" aria-label={'Select '+item.name} checked={selected.includes(item.id)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,item.id]:ids.filter(id=>id!==item.id))}/> Select project</label>}<button className="projectCover" disabled={busy||trash} onClick={()=>onOpen(item)} aria-label={'Open '+item.name}>{item.thumbnail?<img src={item.thumbnail} alt=""/>:<span>▶</span>}<small>{item.project.clips.length} clips · {item.project.width} × {item.project.height}</small></button>
 {renaming===item.id?<form onSubmit={e=>{e.preventDefault();if(draft.trim()){onEdit(item.id,{name:draft.trim()});setRenaming(null);}}}><input aria-label="Rename project" maxLength={100} value={draft} onChange={e=>setDraft(e.target.value)}/><button disabled={busy||!draft.trim()}>Save name</button><button type="button" onClick={()=>setRenaming(null)}>Cancel</button></form>:<h3>{item.pinned?'★ ':''}{item.name}</h3>}<div className="projectCardMeta"><span className="projectBadge">{item.pinned?'Pinned':'Local'}</span>{item.backups.length>0&&<span>{item.backups.length} recovery {item.backups.length===1?'copy':'copies'}</span>}</div><p>Edited {new Date(item.updatedAt).toLocaleString()}</p>
 <div className="projectCardActions">{trash?<button disabled={busy} onClick={()=>onEdit(item.id,{deleted:false})}>Restore project</button>:<><button disabled={busy} onClick={()=>{setRenaming(item.id);setDraft(item.name);}}>Rename</button><button disabled={busy} onClick={()=>onEdit(item.id,{pinned:!item.pinned})}>{item.pinned?'Unpin':'Pin'}</button><button disabled={busy} onClick={()=>onDuplicate(item)}>Duplicate</button><button disabled={busy||!item.backups.length} onClick={()=>setRecover(recover===item.id?null:item.id)}>Recovery</button><button disabled={busy} onClick={()=>{if(confirm('Move “'+item.name+'” to Trash? Original video and audio files will not be deleted.'))onEdit(item.id,{deleted:true});}}>Trash</button></>}</div>
 {recover===item.id&&<div className="recoveryList"><p>Open a recovery version as a separate project:</p>{item.backups.map((b,i)=><button disabled={busy} key={i} onClick={()=>onRecover(item,b)}>{new Date(b.at).toLocaleString()} · {b.project.clips.length} clips</button>)}</div>}</article>)}</div>
 {!shown.length&&<div className="homeEmpty"><strong>{trash?'Trash is empty.':query?'No projects match your search.':'Create your first project, or open a saved .rancut.json file.'}</strong>{!trash&&<div className="emptyActions">{query?<button onClick={()=>setQuery('')}>Clear search</button>:<><button className="primary" onClick={()=>onNew?.('Untitled project')}>+ Start new project</button><button onClick={onImport}>Open project file</button></>}</div>}</div>}
 <footer>RanCut · 0.5.8 Preview · Local editing, original media stays yours.</footer></section>;
}
