import React,{useState,useRef,useEffect} from 'react';
import * as C from './creator.js';
import {applyTransitions} from './creator-workflow.js';
import {importSound} from './sounds.js';
export default function TransitionPicker({project,rightId,onClose,commit,seek}){
 const anchor=project.clips.find(c=>c.id===rightId),[track,setTrack]=useState(anchor?.trackId||project.creatorSource||project.tracks.find(t=>t.type==='video')?.id||''),[id,setId]=useState(rightId||''),[preset,setPreset]=useState(anchor?.transition?C.validateTransition(anchor.transition):C.transitionPreset()),[all,setAll]=useState(false),[replace,setReplace]=useState(false),[error,setError]=useState('');
 const dialog=useRef(),soundInput=useRef(),presetInput=useRef();useEffect(()=>{dialog.current.showModal();return()=>dialog.current?.close();},[]);
 const cuts=C.cutPairs(project,track),target=cuts.find(x=>x.right.id===id)?.right||cuts[0]?.right;
 const apply=()=>{try{const q=applyTransitions(project,{trackId:track,rightId:target?.id,preset,all,replace});if(commit(q,'Transition and sound settings applied'))onClose();}catch(e){setError(e.message);}};
 const save=()=>{try{const v=C.validateTransition(preset),url=URL.createObjectURL(new Blob([JSON.stringify(v,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='RanCut-'+v.kind+'-transition.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e.message);}};
 return <dialog ref={dialog} className="workflowDialog" onCancel={onClose}><header><div><h2>Transitions</h2><p>Attached directly to cuts — not a separate layer.</p></div><button aria-label="Close transitions" onClick={onClose}>×</button></header>
 <div className="workflowBody"><div className="transitionChoices">{C.transitionKinds.map(kind=><button className={preset.kind===kind?'chosen':''} key={kind} onClick={()=>setPreset({...C.transitionPreset(kind),sound:preset.sound,gainDb:preset.gainDb})}><span>{({paper:'▱',whoosh:'➜',shutter:'◧',glitch:'▤',fade:'◑'})[kind]}</span>{kind}</button>)}</div>
 <label>Main video track<select aria-label="Transition main track" value={track} onChange={e=>{setTrack(e.target.value);setId('');}}>{project.tracks.filter(t=>t.type==='video').map(t=><option key={t.id} value={t.id}>{t.name||t.id}</option>)}</select></label>
 <label>Apply to<select aria-label="Transition scope" value={all?'all':'cut'} onChange={e=>setAll(e.target.value==='all')}><option value="cut">This cut only</option><option value="all">Full video — all cuts on this track</option></select></label>
 {!all&&<label>Cut<select aria-label="Transition cut" value={target?.id||''} onChange={e=>setId(e.target.value)}>{!cuts.length&&<option value="">No touching cuts</option>}{cuts.map(({right})=><option value={right.id} key={right.id}>{right.start.toFixed(2)}s · {right.name}</option>)}</select></label>}
 <label>Duration (seconds)<input aria-label="Transition duration" type="number" min=".1" max="2" step=".05" value={preset.duration} onChange={e=>setPreset({...preset,duration:+e.target.value})}/></label>
 <label className="check"><input aria-label="Include transition sound" type="checkbox" checked={preset.sound} onChange={e=>setPreset({...preset,sound:e.target.checked})}/> Include matching sound</label>
 {preset.sound&&<><label>Sound volume (dB)<input aria-label="Transition sound volume" type="number" min="-60" max="6" value={preset.gainDb} onChange={e=>setPreset({...preset,gainDb:+e.target.value})}/></label><button onClick={()=>soundInput.current.click()}>{preset.customSound?'Replace custom sound':'Use my own sound…'}</button><small>Built-in sound matches the transition. Custom sound can be up to 5 seconds.</small></>}
 <label className="check"><input type="checkbox" checked={replace} onChange={e=>setReplace(e.target.checked)}/> Replace existing transitions in this scope</label>
 <div className="workflowActions"><button onClick={save}>Export preset</button><button onClick={()=>presetInput.current.click()}>Import preset</button><button disabled={!target?.transition} onClick={()=>{seek(Math.max(0,target.start-preset.duration/2));onClose();}}>Preview existing · Space to play</button><button disabled={!target?.transition} onClick={()=>{if(commit(p=>({...p,clips:p.clips.map(c=>c.id===target.id?{...c,transition:undefined}:c)}),'Transition removed'))onClose();}}>Remove this transition</button></div>
 <input hidden ref={soundInput} type="file" accept="audio/*" onChange={async e=>{try{const f=e.target.files[0];if(f)setPreset({...preset,customSound:await importSound(f),sound:true});}catch(e){setError(e.message);}finally{e.target.value='';}}}/><input hidden ref={presetInput} type="file" accept=".json" onChange={async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>2000000)throw Error('Preset too large.');setPreset(C.validateTransition(JSON.parse(await f.text())));}catch(e){setError(e.message);}finally{e.target.value='';}}}/>
 {error&&<p role="alert" className="exportError">{error}</p>}</div><footer><button onClick={onClose}>Cancel</button><button className="primary" disabled={!cuts.length} onClick={apply}>Apply transition{preset.sound?' + sound':''}</button></footer></dialog>;
}
