import React,{useEffect,useState} from 'react';
export default function UpdatePanel(){
 const [info,setInfo]=useState({phase:'idle'}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{window.rancut?.updateStatus?.().then(setInfo).catch(e=>setMessage(e.message));return window.rancut?.onUpdate?.(setInfo);},[]);
 async function run(fn){setBusy(true);setMessage('');try{if(!fn)throw Error('Updates are available in the desktop app.');const result=await fn();if(result&&typeof result==='object')setInfo(result);}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 const noRelease=info.releaseState==='none';
 const upToDate=noRelease||(info.releaseState==='published'&&!info.available&&!info.blocked);
 const statusText=message||info.error||(upToDate?`You're using RanCut ${info.current||'0.6.1'}. No newer installer has been published yet.`:info.phase==='idle'?'Click Check for updates to refresh the release channel.':'');
 return <><div className="helpEyebrow">UPDATES</div><h3>Keep RanCut current</h3><p>Installed: {info.current||'0.6.1'} {info.latest&&' · Latest: '+info.latest}</p><p className="helpMuted">Automatic update check: daily</p><button disabled={busy||info.phase==='downloading'} onClick={()=>run(window.rancut?.checkUpdates)}>Check for updates</button>{upToDate&&<div className="helpCallout"><b>You’re up to date</b><span>RanCut {info.current||'0.6.1'} is installed. There is no newer public installer yet.</span></div>}{info.available&&<div className="helpCallout"><b>RanCut {info.latest}</b><span>{info.release?.notes}</span><span>{Math.round((info.release?.size||0)/1048576)} MB</span>{info.phase!=='downloading'&&info.phase!=='ready'&&<button disabled={busy} onClick={()=>run(window.rancut?.openUpdate)}>Download update</button>}</div>}{info.phase==='downloading'&&<><progress max={info.total||1} value={info.received||0}/><p>{Math.floor(100*(info.received||0)/(info.total||1))}% downloaded</p><button onClick={()=>run(window.rancut?.cancelUpdate)}>Cancel download</button></>}{info.phase==='ready'&&<div className="helpCallout"><b>Installer verified</b><span>Saved in Downloads / RanCut Updates. Save your work before installing; Windows may request permission.</span><button disabled={busy} onClick={()=>run(window.rancut?.installUpdate)}>Install now</button></div>}{(info.warning||info.blocked)&&<p>{info.blocked?'Update required to use Auto Edit.':`Required update: ${info.daysRemaining} days remaining.`} Projects, saving and exports stay available.</p>}<p role="status">{statusText}</p></>;
}
