import React,{useEffect,useRef,useMemo} from 'react';
import {scaledPeak} from './timeline-view.js';
import {clamp} from './timeline.js';
export function pyramid(peaks){const levels=[Float32Array.from(peaks)];while(levels.at(-1).length>4){const a=levels.at(-1),b=new Float32Array(Math.ceil(a.length/4)*2);for(let i=0;i<a.length;i+=4){b[i/2]=Math.min(a[i],a[i+2]??0);b[i/2+1]=Math.max(a[i+1],a[i+3]??0);}levels.push(b);}return levels;}
export default function Waveform({clip,media,zoom,scroll,viewport,onGain}){
 const db=clip.fx?.gainDb??0;
 const ref=useRef(),levels=useMemo(()=>pyramid(media?.peaks||[]),[media?.peaks]);const width=clip.duration*zoom,start=clip.start*zoom,left=Math.max(0,scroll-start),visible=Math.max(0,Math.min(width-left,viewport));
 useEffect(()=>{const canvas=ref.current;if(!canvas)return;const ratio=window.devicePixelRatio||1;canvas.width=Math.max(1,Math.ceil(visible*ratio));canvas.height=70*ratio;const ctx=canvas.getContext('2d');ctx.scale(ratio,ratio);ctx.clearRect(0,0,visible,70);if(!media?.peaks?.length)return;const step=media.peakStep||.005,perPixel=1/(zoom*step),level=Math.max(0,Math.min(levels.length-1,Math.floor(Math.log2(Math.max(1,perPixel))))),data=levels[level],bucket=step*2**level;ctx.lineWidth=1;for(let x=0;x<visible;x++){const source=clip.sourceIn+(left+x)/zoom,a=Math.max(0,Math.floor(source/bucket)),b=Math.min(data.length/2,Math.max(a+1,Math.ceil((source+1/zoom)/bucket)));let lo=0,hi=0;for(let i=a;i<b;i++){lo=Math.min(lo,data[i*2]);hi=Math.max(hi,data[i*2+1]);}const peak=scaledPeak(lo,hi,db);ctx.strokeStyle=peak.clipped?'#ff8585':'#a3d3b8';ctx.beginPath();ctx.moveTo(x+.5,35-peak.hi*28);ctx.lineTo(x+.5,35-peak.lo*28);ctx.stroke();}},[clip.sourceIn,clip.duration,zoom,left,visible,levels,media,db]);
 const y=clamp(35-db*1.6,6,66);
 const drag=e=>{e.stopPropagation();e.preventDefault();const sy=e.clientY;const move=ev=>onGain(Math.round(clamp(db+(sy-ev.clientY)/1.6,-60,12)*10)/10);const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true});};
 return <><canvas className="waveCanvas" ref={ref} style={{left,width:visible,height:70}}/><div className="gainLine" style={{top:y}} onPointerDown={drag} title={`${db.toFixed(1)} dB — drag to change gain`}><span style={{left:Math.min(left+8,Math.max(0,width-45))}}>{db.toFixed(1)} dB</span></div></>;
}
